/**
 * Furniture domain barrel.
 *
 * The café's era-varying furniture and soft decor: the module itself, its five
 * per-year specs, the placement vocabulary (plans, props, bounds, placement
 * rules) and the procedural surface pipeline. Import from here or straight from
 * `./FurnitureModule`; the period registry and the app composition layer are the
 * intended consumers.
 */

export {
  DEFAULT_FURNITURE_SEED,
  FURNITURE_ERA_DISCRIMINATOR_FIELDS,
  FURNITURE_GROUP_NAME,
  FURNITURE_MODULE_ID,
  FURNITURE_SPECS,
  FURNITURE_SPEC_YEARS,
  DOORWAY_APPROACH_DEPTH,
  DOOR_SWING_DEPTH,
  FurnitureModule,
  createFurnitureModule,
  describeFurnitureSpec,
  furnitureEraConflicts,
  furniturePlanSignature,
  furnitureSpec,
  furnitureSpecs,
  planFurniture,
  placementProblems,
  placementRules,
  propBounds,
  propFootprint,
  rectsOverlap,
  worldExtents,
} from './FurnitureModule';
export type {
  BanquetteKind,
  BanquetteSpec,
  BenchKind,
  BenchSpec,
  BinKind,
  BinSpec,
  BoothKind,
  BoothSpec,
  ChairKind,
  ChairSpec,
  ClockKind,
  ClockSpec,
  CoatStandKind,
  CoatStandSpec,
  CounterFrontKind,
  CounterFrontSpec,
  FixtureSpec,
  FurnitureBuildInput,
  FurnitureGroup,
  FurnitureModuleDescription,
  FurnitureModuleOptions,
  FurniturePlan,
  FurniturePlanInput,
  FurnitureSpec,
  FurnitureSpecSummary,
  HatRackKind,
  HatRackSpec,
  LoungeKind,
  LoungeSpec,
  MagazineRackKind,
  MagazineRackSpec,
  PhoneKind,
  PhoneSpec,
  PlacementRules,
  PlantKind,
  PlantPlacement,
  PlantSpec,
  PlacedProp,
  PropBuildResult,
  PropKind,
  PropPlanEntry,
  PropRect,
  PropSize,
  PropSupport,
  RailKind,
  RailSpec,
  RugKind,
  RugSpec,
  SeatingSpec,
  SoftDecorSpec,
  StoolKind,
  StoolSpec,
  TableBaseKind,
  TableDecorItem,
  TableDecorItemKind,
  TableShape,
  TableSpec,
  TableSurfaceKind,
  TableVariant,
  WindowTreatmentKind,
  WindowTreatmentSpec,
} from './FurnitureModule';

export {
  FURNITURE_MATERIAL_SLOTS,
  boxMesh,
  createFurnitureMaterialSet,
  cylinderMesh,
  disposeFurnitureMaterialSet,
  furnitureMaterial,
  furnitureMaterialName,
  furnitureMaterialSetMaterials,
  furnitureMaterialSetSignature,
  furnitureRecipe,
  isFurnitureMaterialSlot,
  propMesh,
  sphereMesh,
  torusMesh,
  wallMountTransform,
  yawForDirection,
} from './materials';
export type {
  FurnitureMaterialRecipe,
  FurnitureMaterialSet,
  FurnitureMaterialSetOptions,
  FurnitureMaterialSlot,
  FurnitureMaterialSource,
  FurnitureRecipeOptions,
  PropMeshOptions,
  WallMountTransform,
} from './materials';

export {
  DEFAULT_FURNITURE_TEXTURE_SIZE,
  FURNITURE_TEXTURE_PREFIX,
  Raster,
  createFurnitureTexture,
  defaultCanvasFactory,
  distinctPixelColors,
  hashString,
  isFurnitureTexture,
  mixRgb,
  paintFurnitureSurface,
  parseColor,
  shade,
} from './textures';
export type {
  CanvasFactory,
  FurnitureTexture,
  FurnitureTextureKind,
  FurnitureTextureOptions,
  FurnitureTexturePalette,
  FurnitureTextureStyle,
  Rgb,
} from './textures';
