/**
 * Composition tests: citizens and the vehicle fleet running together on the
 * foundation engine.
 *
 * This suite wires the upstream pieces together the way the app composition
 * will: the seeded `CityWorld` (roads, homes, workplaces, venues), the fixture
 * `SimulationEngine` with its fixed-step clock, `CitizensSystem` and
 * `VehiclesSystem`. It then advances real simulated time and asserts the
 * integrated behaviour the product requires: commuter demand generated by the
 * citizens' own daily schedules produces road traffic, at least ten vehicles
 * are active simultaneously through the commuter peaks across car, bus and
 * delivery-van kinds, commuters are picked up and dropped at the buildings
 * their schedules name, the fleet stays inside the road network, and a full
 * simulated day (and a second one) ends with a bounded, recycling fleet.
 */

import { describe, expect, it } from 'vitest';

import { CitizensSystem, CITIZENS_SYSTEM_NAME } from '../../src/sim/citizens';
import { MINUTES_PER_HOUR } from '../../src/sim/clock';
import {
  MIN_ACTIVE_VEHICLES,
  VEHICLES_SYSTEM_NAME,
  VehiclesSystem,
  vehicleKindForCommuteMode,
} from '../../src/sim/vehicles';
import { createCityWorld } from '../../src/sim/world';
import type { CityWorld } from '../../src/sim/world';
import { createSimFixture, SIM_DAY_MINUTES } from '../helpers/sim-fixtures';
import type { SimFixture } from '../helpers/sim-fixtures';

const SERVICE_HOURS: readonly [number, number][] = [
  [5, 10],
  [16, 21],
];

function isPeakHour(hour: number): boolean {
  return SERVICE_HOURS.some(([start, end]) => hour >= start && hour < end);
}

interface Composition {
  readonly fixture: SimFixture;
  readonly world: CityWorld;
  readonly citizens: CitizensSystem;
  readonly vehicles: VehiclesSystem;
}

function createComposition(seed: string): Composition {
  const fixture = createSimFixture({ seed, startHour: 0, minutesPerTick: 1 });
  const world = createCityWorld({ seed: fixture.rng.seed });
  const citizens = new CitizensSystem({ world, count: 72, seed: fixture.rng.seed });
  const vehicles = new VehiclesSystem({ world, citizens });
  // The integration owner path: engine attaches citizens, then traffic.
  fixture.engine.attach(citizens);
  fixture.engine.attach(vehicles);
  return { fixture, world, citizens, vehicles };
}

/** Per-tick observations the assertions are built from. */
interface PeakLog {
  peakActive: number;
  peakKinds: string[];
  peakMinute: number;
  minActiveInPeak: number;
  offRoad: number;
  outsideWorld: number;
  badNumbers: number;
  boards: number;
  alights: number;
  mismatchedBoards: number;
  mismatchedAlights: number;
  linkedCitizens: Set<string>;
  worldMismatches: number;
}

function emptyPeakLog(): PeakLog {
  return {
    peakActive: 0,
    peakKinds: [],
    peakMinute: -1,
    minActiveInPeak: Number.POSITIVE_INFINITY,
    offRoad: 0,
    outsideWorld: 0,
    badNumbers: 0,
    boards: 0,
    alights: 0,
    mismatchedBoards: 0,
    mismatchedAlights: 0,
    linkedCitizens: new Set<string>(),
    worldMismatches: 0,
  };
}

function roadOffset(vehicle: { position: { x: number; y: number } }, world: CityWorld, fromId: string | null, toId: string | null): number {
  const from = fromId ? world.roadNodeById(fromId) : null;
  const to = toId ? world.roadNodeById(toId) : null;
  if (!from || !to) {
    return 0;
  }
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  const length = Math.hypot(dx, dy) || 1;
  return Math.abs((vehicle.position.x - from.x) * dy - (vehicle.position.y - from.y) * dx) / length;
}

describe('citizens + vehicles on the fixture engine', () => {
  it('puts at least ten vehicles on the road through the commuter peaks', () => {
    const { fixture, world, citizens, vehicles } = createComposition('vehicles-composition');
    const morning = emptyPeakLog();
    const evening = emptyPeakLog();
    const intents = new Map<string, { from: string; to: string }>();
    let serviceHourMinActive = Number.POSITIVE_INFINITY;
    let peakKindsMorningSeen = new Set<string>();
    let peakKindsEveningSeen = new Set<string>();

    try {
      // The composition wiring itself.
      expect(fixture.engine.getSystem(CITIZENS_SYSTEM_NAME)).toBe(citizens);
      expect(fixture.engine.getSystem(VEHICLES_SYSTEM_NAME)).toBe(vehicles);
      expect(fixture.engine.systems.map((system) => system.name)).toEqual([
        'alpha',
        'beta',
        CITIZENS_SYSTEM_NAME,
        VEHICLES_SYSTEM_NAME,
      ]);

      const observe = (log: PeakLog, sampleKinds: Set<string>): void => {
        const hour = fixture.clock.hourOfDay;
        if (!isPeakHour(hour)) {
          return;
        }
        const active = vehicles.activeCount;
        log.minActiveInPeak = Math.min(log.minActiveInPeak, active);
        if (active > log.peakActive) {
          log.peakActive = active;
          log.peakMinute = fixture.clock.totalMinutes;
          log.peakKinds = Object.entries(vehicles.kindCounts())
            .filter(([, count]) => count > 0)
            .map(([kind]) => kind);
        }
        for (const [kind, count] of Object.entries(vehicles.kindCounts())) {
          if (count > 0) {
            sampleKinds.add(kind);
          }
        }
      };

      for (let tick = 1; tick <= 21 * MINUTES_PER_HOUR; tick += 1) {
        const boardsBefore = vehicles.stats().boardings;
        const alightsBefore = vehicles.stats().alightings;
        fixture.engine.step(1);
        const hour = fixture.clock.hourOfDay;
        const log = hour >= 16 ? evening : morning;
        for (const intent of citizens.pendingCommuteIntents()) {
          intents.set(intent.citizenId, { from: intent.fromBuildingId, to: intent.toBuildingId });
        }
        const newBoards = vehicles.stats().boardings - boardsBefore;
        const newAlights = vehicles.stats().alightings - alightsBefore;
        // `slice(-0)` would re-read the whole log, so only look when there is news.
        const boardEvents = newBoards > 0 ? vehicles.eventsOfKind('board').slice(-newBoards) : [];
        const alightEvents = newAlights > 0 ? vehicles.eventsOfKind('alight').slice(-newAlights) : [];
        for (const event of boardEvents) {
          const intent = event.citizenId ? intents.get(event.citizenId) : undefined;
          if (intent && intent.from === event.buildingId) {
            log.boards += 1;
          } else {
            log.mismatchedBoards += 1;
          }
        }
        for (const event of alightEvents) {
          const intent = event.citizenId ? intents.get(event.citizenId) : undefined;
          if (intent && intent.to === event.buildingId) {
            log.alights += 1;
          } else {
            log.mismatchedAlights += 1;
          }
        }
        for (const citizen of citizens.citizens) {
          if (citizen.vehicleId !== null) {
            const details = vehicles.detailsFor(citizen.vehicleId);
            if (details?.occupantIds.includes(citizen.id)) {
              log.linkedCitizens.add(citizen.id);
            }
          }
        }
        for (const vehicle of world.vehicles) {
          if (roadOffset(vehicle, world, vehicle.currentNodeId, vehicle.targetNodeId) > 1e-9) {
            log.offRoad += 1;
          }
          if (
            vehicle.position.x < 0 ||
            vehicle.position.y < 0 ||
            vehicle.position.x > world.widthInTiles ||
            vehicle.position.y > world.heightInTiles ||
            !Number.isFinite(vehicle.position.x) ||
            !Number.isFinite(vehicle.position.y) ||
            !Number.isFinite(vehicle.speed)
          ) {
            log.outsideWorld += 1;
          }
          if (vehicle.occupancy !== vehicle.occupantIds.length) {
            log.badNumbers += 1;
          }
        }
        if (world.vehicles.length !== vehicles.activeCount) {
          log.worldMismatches += 1;
        }
        if (hour >= 5 && hour < 23) {
          serviceHourMinActive = Math.min(serviceHourMinActive, vehicles.activeCount);
        }
        observe(log, hour >= 16 ? peakKindsEveningSeen : peakKindsMorningSeen);

        // The citizen roster keeps producing travel demand all day long.
        if (tick === 9 * MINUTES_PER_HOUR) {
          expect(citizens.stats().travellingCount).toBeGreaterThan(0);
        }
      }

      for (const [label, log, kinds] of [
        ['morning', morning, peakKindsMorningSeen],
        ['evening', evening, peakKindsEveningSeen],
      ] as const) {
        expect(log.peakActive, label).toBeGreaterThanOrEqual(MIN_ACTIVE_VEHICLES);
        expect(log.minActiveInPeak, label).toBeGreaterThanOrEqual(MIN_ACTIVE_VEHICLES);
        expect(log.peakKinds, label).toContain('car');
        expect(log.peakKinds, label).toContain('bus');
        expect(log.peakKinds, label).toContain('truck');
        expect(log.peakKinds.length, label).toBeGreaterThanOrEqual(3);
        expect(log.offRoad, label).toBe(0);
        expect(log.outsideWorld, label).toBe(0);
        expect(log.badNumbers, label).toBe(0);
        expect(log.mismatchedBoards, label).toBe(0);
        expect(log.mismatchedAlights, label).toBe(0);
        expect(log.boards, label).toBeGreaterThan(0);
        expect(log.alights, label).toBeGreaterThan(0);
        expect(log.linkedCitizens.size, label).toBeGreaterThan(0);
        expect(log.worldMismatches, label).toBe(0);
        // Car, bus, van, tram and bicycle all appear over the peak.
        expect(kinds.size, label).toBeGreaterThanOrEqual(3);
      }
      expect(serviceHourMinActive).toBeGreaterThanOrEqual(MIN_ACTIVE_VEHICLES);
      expect(vehicles.stats().expiredWaits).toBe(0);
      expect(vehicles.stats().unservedIntents).toBe(0);

      // Demand inputs: commute corridors come from the citizens' own routines,
      // freight runs from the city's warehouses, factories and shops.
      const corridors = vehicles.commuteCorridors();
      expect(corridors.length).toBeGreaterThan(10);
      for (const corridor of corridors) {
        expect(citizens.buildingById(corridor.fromBuildingId)).not.toBeNull();
        expect(citizens.buildingById(corridor.toBuildingId)).not.toBeNull();
        expect(corridor.fromNodeId).not.toBe(corridor.toNodeId);
        expect(vehicleKindForCommuteMode(corridor.mode)).toBe(corridor.kind);
      }
      expect(corridors.some((corridor) => corridor.kind === 'bus')).toBe(true);
      expect(corridors.some((corridor) => corridor.kind === 'car')).toBe(true);
      expect(vehicles.transitCorridors().length).toBeGreaterThan(0);
      const runs = vehicles.freightRuns();
      expect(runs.length).toBeGreaterThan(0);
      for (const run of runs) {
        expect(world.buildingById(run.sourceBuildingId)).not.toBeNull();
        expect(world.buildingById(run.destinationBuildingId)).not.toBeNull();
        expect(run.vehicleKind).toBe('truck');
        expect(run.distanceTiles).toBeGreaterThan(0);
      }
      expect(vehicles.stats().freightDeliveries).toBeGreaterThan(0);

      // The inspector can describe the traffic it sees.
      const sample = vehicles.activeVehicles()[0];
      if (sample) {
        const details = vehicles.detailsFor(sample.id);
        expect(details?.plate).toBe(sample.plate);
        expect(details?.capacity).toBeGreaterThanOrEqual(1);
        expect(details?.role).not.toBeUndefined();
        expect(details?.stops.length).toBeGreaterThan(0);
      }
    } finally {
      fixture.dispose();
    }
  }, 240_000);

  it('serves two full simulated days with a bounded, recycling fleet', () => {
    const { fixture, world, citizens, vehicles } = createComposition('vehicles-two-days');
    const boardingsPerDay: { day: number; boards: number; alights: number; peak: number; nightActive: number }[] = [];
    let peakActive = 0;
    let offRoad = 0;
    try {
      for (let tick = 1; tick <= 2 * SIM_DAY_MINUTES; tick += 1) {
        fixture.engine.step(1);
        peakActive = Math.max(peakActive, vehicles.activeCount);
        expect(vehicles.activeCount).toBeLessThanOrEqual(vehicles.maxActiveVehicles);
        for (const vehicle of world.vehicles) {
          if (roadOffset(vehicle, world, vehicle.currentNodeId, vehicle.targetNodeId) > 1e-9) {
            offRoad += 1;
          }
        }
        // 02:00 is deep enough into the night that demand has gone home and the
        // fleet has fallen back to its overnight skeleton.
        if (fixture.clock.minuteOfHour === 0 && fixture.clock.hourOfDay === 2) {
          boardingsPerDay.push({
            day: fixture.clock.day,
            boards: vehicles.stats().boardings,
            alights: vehicles.stats().alightings,
            peak: vehicles.stats().peakActiveVehicles,
            nightActive: vehicles.activeCount,
          });
        }
      }

      expect(offRoad).toBe(0);
      expect(peakActive).toBeGreaterThanOrEqual(MIN_ACTIVE_VEHICLES);
      expect(vehicles.stats().boardings).toBeGreaterThan(200);
      expect(vehicles.stats().alightings).toBeGreaterThan(150);
      expect(vehicles.stats().parks).toBeGreaterThan(100);
      // Two mornings were submitted to the floor: the fleet was topped back up
      // after every night, which is what keeps the city moving for days.
      expect(boardingsPerDay.length).toBeGreaterThanOrEqual(2);
      for (const day of boardingsPerDay) {
        // Even overnight the promised floor holds; the peak adds demand on top.
        expect(day.nightActive, `day ${day.day}`).toBeGreaterThanOrEqual(MIN_ACTIVE_VEHICLES);
        expect(day.peak, `day ${day.day}`).toBeGreaterThan(day.nightActive);
      }
      expect(boardingsPerDay[1].boards).toBeGreaterThan(boardingsPerDay[0].boards);
      expect(vehicles.stats().reusedVehicles).toBeGreaterThan(50);
      expect(vehicles.stats().createdVehicles).toBeLessThanOrEqual(vehicles.maxActiveVehicles);
      expect(vehicles.stats().activeVehicles).toBeLessThanOrEqual(vehicles.maxActiveVehicles);
      expect(world.vehicles.length).toBe(vehicles.activeCount);
      expect(citizens.citizens).toHaveLength(72);

      // Detaching the traffic system empties the network but keeps its objects.
      fixture.engine.detach(vehicles);
      expect(vehicles.activeCount).toBe(0);
      expect(world.vehicles).toHaveLength(0);
      expect(vehicles.parkedCount).toBeGreaterThanOrEqual(MIN_ACTIVE_VEHICLES);
    } finally {
      fixture.dispose();
    }
  }, 240_000);
});

