/**
 * Chrono City — era storefronts and advertising for the block's ground floor.
 *
 * `StorefrontsApi` is the single entry point the app (and later the era-transition
 * integration task) talks to. It owns the `0–4 m` shopfront band of every lot and
 * morphs it through the five eras:
 *
 *   * it plans every lot per era (`planShopfront` + `planAdvertising`) up front, so
 *     per-year shop names, blurbs and media are known before any geometry exists;
 *   * it builds one *variant* per `(lot, era)` lazily — frame, glazing, door,
 *     display bay, window dressing, awning, fascia sign, blade sign, transom ad
 *     strip and (on landmark and every-third lots) freestanding kerb media —
 *     painting every face from the shared sign-texture factory;
 *   * it implements `EraBlendable`: `setEra()` starts a transition and
 *     `updateEraTransition()` is called once per frame by the `TimelineRuntime`
 *     tween, cross-fading the shopfronts and ad media of the two eras so the
 *     street is never empty and never cuts;
 *   * it registers every shop and every billboard in the `InspectionRegistry`
 *     with per-year names and blurbs, on stable lot groups so the picked object
 *     does not change under the picker while eras morph;
 *   * it registers a `SceneContext` tick system that walks the animated media
 *     (neon flicker, marquee chase, video reels, LED scroll, hologram shimmer)
 *     with pure UV/emissive updates, inside the frame budget.
 *
 * Ownership boundaries (deliberate):
 *   * **The band is ours.** Meshes tagged with the band roles in `BAND_ROLES`
 *     never leave `y ∈ [0, 4]`; the only freestanding geometry (`billboard` /
 *     `ground-fixture`) stands on the sidewalk, never on the building line.
 *   * **Buildings own everything above.** This module consumes the buildings
 *     task's mount surfaces (`mountSurfaceList()` is structurally compatible) and
 *     never touches facade or roof geometry.
 *   * **Materials and textures come from the library.** One era resolves at most
 *     `MAX_STOREFRONT_MATERIALS_PER_ERA` materials, shared across all eighteen
 *     lots, and every sign face is a canvas texture generated by the material
 *     library's surface generators — no font files, no image fetches.
 *
 * Lifecycle:
 *   create    → `createStorefrontsApi({ context, timeline, materials, registry })`.
 *   consume   → `api.snapshot()`, `api.featuresFor(era)`, `api.shopNameFor(lot, era)`,
 *               `api.lotObject(lotId)` / `api.billboardObject(lotId)`.
 *   integrate → the era-transition task wires it into `main.ts`:
 *
 *   ```ts
 *   const buildings = createBuildingsApi({ context, timeline, registry });
 *   const storefronts = createStorefrontsApi({
 *     context,
 *     timeline,
 *     registry,
 *     mountSurfaces: buildings.mountSurfaceList(),
 *     materials,
 *   });
 *   ```
 */

import * as THREE from 'three';

import {
  DEFAULT_ERA,
  ERA_IDS,
  assertEraId,
  clamp01,
  type EraBlendable,
  type EraId,
  type EraTransitionInfo,
  type EraTransitionOptions,
} from '../../core/eraContracts';
import type {
  FrameInfo,
  RandomSource,
  SceneContext,
  SystemRegistration,
} from '../../core/sceneContext';
import type { EraBlendableRegistration, TimelineRuntime } from '../../era/timelineRuntime';
import type {
  InspectableCopyByEra,
  InspectableDefinition,
  InspectionRegistry,
} from '../../interaction/inspectionRegistry';
import {
  DetailGeometrySet,
  type DetailGeometrySet as GeometrySetType,
} from '../buildings/buildingFactory';
import { createMaterialLibraryFromScene, type MaterialLibrary } from '../../materials/materialLibrary';
import {
  createSignMaterialHandle,
  createSignTexture,
  signFaceKey,
  type SignFaceSpec,
  type SignMaterialHandle,
  type SignMedia,
  type SignTextBlock,
} from './signTextures';
import {
  addShopfrontFeatureCounts,
  buildShopfront,
  createShopfrontFeatureCounts,
  createShopfrontMaterials,
  defaultStorefrontLots,
  getShopArchetypes,
  lotCarriesKerbMedia,
  mountSurfacesFromLots,
  planShopfront,
  MAX_STOREFRONT_MATERIALS_PER_ERA,
  STOREFRONT_BAND_HEIGHT,
  type AwningKind,
  type ShopDressingKind,
  type ShopfrontBuildResult,
  type ShopfrontFeatureCounts,
  type ShopfrontPlan,
  type ShopKind,
  type StorefrontLot,
  type StorefrontMaterialSet,
  type StorefrontMountSurface,
} from './storefrontFactory';
import {
  addAdFeatureCounts,
  advertisementSignSpec,
  buildAdvertisement,
  createAdFeatureCounts,
  createMediaProfile,
  isEmissiveClass,
  mediaClass,
  planAdvertising,
  MEDIA_CLASSES,
  type AdFeatureCounts,
  type AdKind,
  type AdvertisementPlan,
  type MediaClass,
} from './advertisingFactory';

export const STOREFRONTS_API_VERSION = 1;

/** Tick-system id this system registers under. */
export const STOREFRONTS_SYSTEM_ID = 'city-storefronts';

/** Tick order: after the buildings (`-500`), before interaction picking (`10`). */
export const STOREFRONTS_SYSTEM_ORDER = -450;

/** Blendable id handed to the timeline. */
export const STOREFRONTS_BLENDABLE_ID = 'city-storefronts-block';

/** Root group name of the storefront set. */
export const STOREFRONTS_ROOT_NAME = 'chrono-city-storefronts';

/** Prefix of a shop's inspectable id. */
export const STOREFRONT_INSPECTABLE_PREFIX = 'storefront-';

/** Prefix of a billboard's inspectable id. */
export const BILLBOARD_INSPECTABLE_PREFIX = 'billboard-';

/** Progress at which the outgoing era has fully faded away. */
export const SOURCE_FADE_START = 0.24;
export const SOURCE_FADE_END = 0.62;
/** Progress at which the incoming era has fully arrived. */
export const TARGET_RISE_START = 0.14;
export const TARGET_RISE_END = 0.54;

/** Inspectable id of one lot's shopfront. */
export function shopfrontInspectableId(lotId: string): string {
  return `${STOREFRONT_INSPECTABLE_PREFIX}${lotId}`;
}

/** Inspectable id of one lot's billboard. */
export function billboardInspectableId(lotId: string): string {
  return `${BILLBOARD_INSPECTABLE_PREFIX}${lotId}`;
}

/** Weight of the incoming era at tween progress `p`. */
export function targetEraWeight(progress: number): number {
  const p = clamp01(progress);
  return clamp01((p - TARGET_RISE_START) / (TARGET_RISE_END - TARGET_RISE_START));
}

/** Weight of the outgoing era at tween progress `p`. */
export function sourceEraWeight(progress: number): number {
  const p = clamp01(progress);
  return 1 - clamp01((p - SOURCE_FADE_START) / (SOURCE_FADE_END - SOURCE_FADE_START));
}

/* ------------------------------------------------------------------------- *
 * Public shapes
 * ------------------------------------------------------------------------- */

/** One built `(lot, era)` shopfront variant. */
export interface StorefrontVariantHandle {
  readonly lotId: string;
  readonly era: EraId;
  readonly plan: ShopfrontPlan;
  readonly adPlans: readonly AdvertisementPlan[];
  /** Group holding this era's shopfront, signage and in-band advertising. */
  readonly group: THREE.Group;
  /** Group holding this era's freestanding kerb media. */
  readonly billboardGroup: THREE.Group;
  readonly shopfront: ShopfrontBuildResult;
  readonly shopfrontCounts: ShopfrontFeatureCounts;
  readonly adCounts: AdFeatureCounts;
  readonly instances: number;
  readonly meshes: readonly THREE.Mesh[];
  /** Instance counts per advertising media class. */
  readonly mediaProfile: Readonly<Record<MediaClass, number>>;
  /** Signs that animate (neon flicker, chase, video, LED scroll, hologram). */
  readonly animatedFaces: number;
  /** Sum of every referenced face's emissive intensity. */
  readonly glow: number;
  readonly weight: number;
  applyWeight(weight: number): void;
  dispose(): void;
}

/** Per-lot state inside a `StorefrontsSnapshot`. */
export interface StorefrontLotState {
  readonly id: string;
  readonly side: StorefrontLot['side'];
  readonly landmark: boolean;
  readonly era: EraId;
  readonly shopName: string;
  readonly shopKind: ShopKind;
  readonly dressingKinds: readonly ShopDressingKind[];
  readonly awning: AwningKind;
  readonly signMedia: SignMedia;
  readonly bladeMedia: SignMedia;
  readonly transomMedia: SignMedia;
  readonly kerbMedia: SignMedia | null;
  readonly inspectableId: string;
  readonly billboardInspectableId: string | null;
  readonly weightSum: number;
  readonly visibleVariantCount: number;
  readonly instances: number;
  readonly glow: number;
  readonly animatedFaces: number;
}

/** Everything a HUD, a test or the integration task needs to read at once. */
export interface StorefrontsSnapshot {
  readonly version: number;
  readonly era: EraId;
  readonly from: EraId;
  readonly to: EraId;
  readonly progress: number;
  readonly transitioning: boolean;
  readonly lotCount: number;
  readonly registeredInspectables: number;
  readonly builtVariants: number;
  readonly visibleVariants: number;
  readonly shopfrontInstances: number;
  readonly dressingInstances: number;
  readonly awningInstances: number;
  readonly signageInstances: number;
  readonly advertisingInstances: number;
  readonly billboardInstances: number;
  readonly totalInstances: number;
  readonly mediaProfile: Readonly<Record<MediaClass, number>>;
  readonly mediaShare: Readonly<Record<MediaClass, number>>;
  readonly animatedFaces: number;
  readonly glow: number;
  readonly mediaPulse: number;
  readonly tickCount: number;
  readonly elapsed: number;
  readonly materialCount: number;
  readonly materialKeys: readonly string[];
  readonly signTextureCount: number;
  readonly shopNames: readonly string[];
  readonly lots: readonly StorefrontLotState[];
}

/** One era's aggregated feature totals across the whole block. */
export interface StorefrontFeatureSummary {
  readonly era: EraId;
  readonly lots: number;
  readonly shopKinds: readonly ShopKind[];
  readonly shopNames: readonly string[];
  readonly dressingKinds: readonly ShopDressingKind[];
  readonly awningKinds: readonly AwningKind[];
  readonly signMedia: readonly SignMedia[];
  readonly adKinds: readonly AdKind[];
  readonly dressing: Partial<Record<ShopDressingKind, number>>;
  readonly shopfront: ShopfrontFeatureCounts;
  readonly ads: AdFeatureCounts;
  readonly instances: number;
  readonly shopfrontInstances: number;
  readonly dressingInstances: number;
  readonly awningInstances: number;
  readonly signageInstances: number;
  readonly advertisingInstances: number;
  readonly billboardInstances: number;
  readonly mediaProfile: Readonly<Record<MediaClass, number>>;
  readonly mediaShare: Readonly<Record<MediaClass, number>>;
  readonly animatedFaces: number;
  readonly glow: number;
  readonly materialKeys: readonly string[];
  readonly signTextureCount: number;
}

export interface StorefrontsApiOptions {
  /** Shared scene context: supplies the scene, seeded RNG and the tick loop. */
  readonly context: SceneContext;
  /** Timeline driving the era. When given, this API registers as a blendable. */
  readonly timeline?: TimelineRuntime | null;
  /** Shared material library; a scene-seeded one is created when omitted. */
  readonly materials?: MaterialLibrary;
  /** Registry the shops and billboards register in. Omit to register nothing. */
  readonly registry?: InspectionRegistry | null;
  /**
   * Band mount surfaces to dress. Structurally compatible with the buildings
   * task's `mountSurfaceList()`; defaults to the authored lot ring so the
   * storefronts line up with `createBuildingsApi()` with no wiring at all.
   */
  readonly mountSurfaces?: readonly StorefrontMountSurface[] | null;
  /** Object the storefront root is parented to. Defaults to `context.scene`. */
  readonly parent?: THREE.Object3D;
  /** Era to build before the timeline takes over. Defaults to the timeline's. */
  readonly initialEra?: EraId;
  readonly blendableId?: string;
  readonly systemId?: string;
  readonly systemOrder?: number;
  /** Register the animated-media tick system. Defaults to `true`. */
  readonly animate?: boolean;
  /** Register shop/billboard inspectables. Defaults to `true` when a registry is given. */
  readonly registerInspectables?: boolean;
}

interface LotRecord {
  readonly mount: StorefrontMountSurface;
  readonly lot: StorefrontLot;
  /** Stable per-lot group every variant hangs from; also the shop inspectable. */
  readonly group: THREE.Group;
  /** Stable per-lot group for kerb media; also the billboard inspectable. */
  readonly billboardGroup: THREE.Group;
  readonly variants: Map<EraId, StorefrontVariant>;
}

/* ------------------------------------------------------------------------- *
 * Sign copy helpers
 * ------------------------------------------------------------------------- */

/** Short, era-appropriate line painted under a shop's trading name. */
export const ERA_SHOP_TAGLINES: Readonly<Record<EraId, readonly string[]>> = Object.freeze({
  '1945': Object.freeze([
    'EST. 1898',
    'FAMILY BUSINESS SINCE 1919',
    'OPEN 8 TILL 6',
    'HOME DELIVERIES DAILY',
  ]),
  '1965': Object.freeze(['OPEN 24 HOURS', 'SELF SERVICE', 'AIR CONDITIONED', 'PARKING AT REAR']),
  '1985': Object.freeze(['OPEN LATE', 'NEW RELEASES DAILY', 'EVERYTHING UNDER ONE ROOF', 'CALL IN TODAY']),
  '2005': Object.freeze(['OPEN 7 DAYS', 'BROADBAND INSIDE', 'LONG LIFE MILK & MORE', 'OPEN TILL 10']),
  '2025': Object.freeze(['OPEN 24/7', 'SCAN, TAP, GO', 'CARBON NEUTRAL SINCE 2021', 'PICKUP IN 15 MINUTES']),
});

/** Dressing kinds whose props are screens driven by the era's media face. */
const SCREEN_DRESSING_KINDS: readonly ShopDressingKind[] = Object.freeze([
  'arcadeCabinets',
  'tvWall',
  'laptopRows',
  'hologramPlinths',
  'vrRigs',
  'selfCheckout',
]);

/** Human-readable phrase for a media class, used in inspectable copy. */
export function describeMedia(className: MediaClass): string {
  switch (className) {
    case 'painted':
      return 'hand-painted boards';
    case 'paper':
      return 'pasted paper bills';
    case 'neon':
      return 'exposed neon tubes';
    case 'backlit':
      return 'backlit lightboxes';
    case 'print':
      return 'printed price boards';
    case 'video':
      return 'video screens';
    case 'led':
      return 'programmed LED panels';
    default:
      return 'holographic projections';
  }
}

/* ------------------------------------------------------------------------- *
 * Variant
 * ------------------------------------------------------------------------- */

interface VariantBuildInput {
  readonly lot: StorefrontLot;
  readonly plan: ShopfrontPlan;
  readonly adPlans: readonly AdvertisementPlan[];
  readonly materials: StorefrontMaterialSet;
  readonly geometries: GeometrySetType;
  readonly parent: THREE.Group;
  readonly random: RandomSource;
  readonly fascia: SignMaterialHandle;
  readonly decals: SignMaterialHandle;
  readonly menu: SignMaterialHandle;
  readonly valance: SignMaterialHandle | null;
  readonly screen: SignMaterialHandle | null;
  readonly adMedia: readonly (SignMaterialHandle | null)[];
}

/** One lot's shopfronts + advertising for one era. */
class StorefrontVariant implements StorefrontVariantHandle {
  readonly lotId: string;
  readonly era: EraId;
  readonly plan: ShopfrontPlan;
  readonly adPlans: readonly AdvertisementPlan[];
  readonly group: THREE.Group;
  readonly billboardGroup: THREE.Group;
  readonly shopfront: ShopfrontBuildResult;
  readonly shopfrontCounts: ShopfrontFeatureCounts;
  readonly adCounts: AdFeatureCounts;
  readonly instances: number;
  readonly meshes: readonly THREE.Mesh[];
  readonly mediaProfile: Readonly<Record<MediaClass, number>>;
  readonly animatedFaces: number;
  readonly glow: number;
  readonly signHandles: readonly SignMaterialHandle[];
  /** Instances drawn at the sidewalk kerb (billboards, columns, hoardings). */
  readonly billboardInstances: number;
  /** Instances spent on advertising, in band and at the kerb. */
  readonly advertisingInstances: number;

  weight = 1;

  private glowState = 0;
  private pulseState = 0;
  private disposed = false;

  constructor(input: VariantBuildInput) {
    this.lotId = input.lot.id;
    this.era = input.plan.era;
    this.plan = input.plan;
    this.adPlans = input.adPlans;

    this.group = new THREE.Group();
    this.group.name = `storefront-lot:${input.lot.id}@${this.era}`;
    this.group.userData.chronoStorefrontLot = input.lot.id;
    this.group.userData.chronoStorefrontEra = this.era;
    this.billboardGroup = new THREE.Group();
    this.billboardGroup.name = `storefront-billboard:${input.lot.id}@${this.era}`;
    this.billboardGroup.userData.chronoStorefrontLot = input.lot.id;
    this.billboardGroup.userData.chronoStorefrontEra = this.era;
    this.group.add(this.billboardGroup);

    this.shopfront = buildShopfront({
      plan: input.plan,
      materials: input.materials,
      geometries: input.geometries,
      parent: this.group,
      random: input.random,
      fascia: input.fascia,
      decals: input.decals,
      menu: input.menu,
      valance: input.valance,
      screen: input.screen,
    });
    this.shopfrontCounts = this.shopfront.counts;

    const adCounts = createAdFeatureCounts();
    let advertisingInstances = 0;
    let billboardInstances = 0;
    const adMedia: SignMaterialHandle[] = [];
    input.adPlans.forEach((adPlan, index) => {
      const media = input.adMedia[index] ?? null;
      const built = buildAdvertisement({
        plan: adPlan,
        materials: input.materials,
        geometries: input.geometries,
        parent: adPlan.slot === 'kerb' ? this.billboardGroup : this.group,
        random: input.random,
        media,
      });
      addAdFeatureCounts(adCounts, built.counts);
      advertisingInstances += built.instances;
      if (adPlan.slot === 'kerb') billboardInstances += built.instances;
      for (const face of built.signFaces) adMedia.push(face);
    });
    this.adCounts = Object.freeze(adCounts);

    // Unique faces this variant references: the fascia, the era decal sheet, the
    // era dressing screen and every advertisement creative.
    const unique = new Set<SignMaterialHandle>([
      input.fascia,
      input.decals,
      input.menu,
      ...(input.valance ? [input.valance] : []),
      ...(input.screen ? [input.screen] : []),
      ...adMedia,
    ]);
    this.signHandles = Object.freeze([...unique]);

    const mediaProfile = createMediaProfile();
    const addMedia = (media: SignMedia, count: number): void => {
      if (count <= 0) return;
      const bucket = mediaClass(media);
      mediaProfile[bucket] += count;
    };
    addMedia(input.plan.signMedia, 1);
    addMedia(input.plan.signMedia, this.shopfront.counts.decals);
    for (const handle of adMedia) addMedia(handle.media, 1);
    if (input.plan.kerbMedia) addMedia(input.plan.kerbMedia, 1);
    if (input.screen) {
      const screenProps = SCREEN_DRESSING_KINDS.reduce(
        (sum, kind) => sum + (this.shopfront.counts.dressingByKind[kind] ?? 0),
        0,
      );
      addMedia(input.screen.media, screenProps);
    }
    this.mediaProfile = Object.freeze(mediaProfile);

    let glow = 0;
    let animated = 0;
    for (const handle of this.signHandles) {
      glow += handle.baseEmissiveIntensity;
      if (handle.animated) animated += 1;
    }
    this.glow = glow;
    this.animatedFaces = animated;
    this.glowState = glow;

    const meshes: THREE.Mesh[] = [];
    this.group.traverse((object) => {
      if ((object as THREE.Mesh).isMesh) meshes.push(object as THREE.Mesh);
    });
    this.meshes = Object.freeze(meshes);
    this.instances = this.shopfront.instances + advertisingInstances;
    this.billboardInstances = billboardInstances;
    this.advertisingInstances = advertisingInstances;

    input.parent.add(this.group);
  }

  get shopfrontInstances(): number {
    return this.shopfront.instances;
  }

  get dressingInstances(): number {
    return this.shopfront.counts.dressingItems;
  }

  get awningInstances(): number {
    return (
      this.shopfront.counts.awnings +
      this.shopfront.counts.awningValances +
      this.shopfront.counts.awningSupports +
      this.shopfront.counts.awningScallops
    );
  }

  get signageInstances(): number {
    // Lettered and printed faces of the shopfront itself; structural
    // advertising (blades, frames, kerbs) is counted in `advertisingInstances`.
    return this.shopfront.counts.signageFaces + this.shopfront.counts.decals;
  }

  get lastGlow(): number {
    return this.glowState;
  }

  get lastPulse(): number {
    return this.pulseState;
  }

  applyWeight(weight: number): void {
    this.weight = weight;
    const visible = weight > 0.002;
    this.group.visible = visible;
    this.billboardGroup.visible = visible;
  }

  /** Walks every animated face one frame; pure in `elapsedSeconds`. */
  animate(elapsedSeconds: number): { animatedFaces: number; glow: number; pulse: number } {
    if (this.disposed || !this.group.visible) {
      return { animatedFaces: 0, glow: 0, pulse: 0 };
    }
    let glow = 0;
    let pulse = 0;
    for (const handle of this.signHandles) {
      const state = handle.advance(elapsedSeconds);
      glow += state.emissiveIntensity;
      if (state.pulse > pulse) pulse = state.pulse;
    }
    this.glowState = glow;
    this.pulseState = pulse;
    return { animatedFaces: this.animatedFaces, glow, pulse };
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    for (const mesh of this.meshes) {
      if ((mesh as THREE.InstancedMesh).isInstancedMesh) (mesh as THREE.InstancedMesh).dispose();
    }
    this.group.removeFromParent();
    this.group.clear();
    this.billboardGroup.clear();
  }
}

/* ------------------------------------------------------------------------- *
 * API
 * ------------------------------------------------------------------------- */

/**
 * The era-evolving storefront band of the city block.
 *
 * Everything the rest of the app needs is reachable from here: the per-era plans,
 * the morph state, per-era feature totals and the inspectable ids of every shop
 * and billboard.
 */
export class StorefrontsApi implements EraBlendable {
  readonly version = STOREFRONTS_API_VERSION;

  readonly id: string;
  readonly root: THREE.Group;
  readonly lots: readonly StorefrontLot[];
  readonly mountSurfaces: readonly StorefrontMountSurface[];

  private readonly context: SceneContext;
  private readonly timeline: TimelineRuntime | null;
  private readonly registry: InspectionRegistry | null;
  private readonly library: MaterialLibrary;
  private readonly ownsLibrary: boolean;
  private readonly random: SceneContext['random'];
  private readonly geometries = new DetailGeometrySet();
  private readonly records = new Map<string, LotRecord>();
  private readonly plans = new Map<string, ShopfrontPlan>();
  private readonly adPlans = new Map<string, readonly AdvertisementPlan[]>();
  private readonly materialSets = new Map<EraId, StorefrontMaterialSet>();
  private readonly signHandles = new Map<string, SignMaterialHandle>();
  private readonly ownedHandles: SignMaterialHandle[] = [];
  private readonly registeredIds: string[] = [];
  private readonly systemId: string;
  private readonly systemOrder: number;
  private readonly animateMedia: boolean;

  private blendableRegistration: EraBlendableRegistration | null = null;
  private systemRegistration: SystemRegistration | null = null;

  private fromEra: EraId;
  private toEra: EraId;
  private progressState = 1;
  private tickCountState = 0;
  private elapsedState = 0;
  private glowState = 0;
  private animatedFacesState = 0;
  private mediaPulseState = 0;
  private disposedState = false;

  constructor(options: StorefrontsApiOptions) {
    if (!options?.context) throw new TypeError('StorefrontsApi needs a SceneContext.');
    this.context = options.context;
    this.timeline = options.timeline ?? null;
    this.registry = options.registry ?? null;
    this.library = options.materials ?? createMaterialLibraryFromScene(options.context);
    this.ownsLibrary = options.materials === undefined;
    this.random = options.context.random;
    this.id = options.blendableId ?? STOREFRONTS_BLENDABLE_ID;
    this.systemId = options.systemId ?? STOREFRONTS_SYSTEM_ID;
    this.systemOrder = options.systemOrder ?? STOREFRONTS_SYSTEM_ORDER;
    this.animateMedia = options.animate ?? true;

    this.lots = Object.freeze(
      defaultStorefrontLots().filter((lot) =>
        options.mountSurfaces
          ? options.mountSurfaces.some((mount) => mount.lotId === lot.id)
          : true,
      ),
    );
    this.mountSurfaces = Object.freeze([
      ...(options.mountSurfaces ?? mountSurfacesFromLots(this.lots)),
    ]);

    this.root = new THREE.Group();
    this.root.name = STOREFRONTS_ROOT_NAME;

    for (const mount of this.mountSurfaces) {
      const lot = this.lots.find((entry) => entry.id === mount.lotId);
      if (!lot) continue;
      const group = new THREE.Group();
      group.name = `storefront-lot:${lot.id}`;
      group.position.set(mount.position.x, 0, mount.position.z);
      group.rotation.y = mount.yaw;
      group.userData.chronoStorefrontLot = lot.id;
      group.userData.chronoStorefrontSide = lot.side;
      const billboardGroup = new THREE.Group();
      billboardGroup.name = `storefront-billboard:${lot.id}`;
      billboardGroup.userData.chronoStorefrontLot = lot.id;
      group.add(billboardGroup);
      this.root.add(group);
      this.records.set(lot.id, { mount, lot, group, billboardGroup, variants: new Map() });
    }

    (options.parent ?? options.context.scene).add(this.root);
    this.root.updateMatrixWorld(true);

    if (options.registerInspectables ?? this.registry !== null) {
      if (this.registry) this.registerInspectables();
    }

    const initial = options.initialEra ?? this.timeline?.era ?? DEFAULT_ERA;
    this.fromEra = assertEraId(initial);
    this.toEra = this.fromEra;
    this.applyMorph();

    if (this.timeline) {
      this.blendableRegistration = this.timeline.registerBlendable(this, { id: this.id });
    }

    if (this.animateMedia) {
      this.systemRegistration = this.context.registerSystem(this.systemId, this.tick, {
        order: this.systemOrder,
      });
    }
  }

  /* ---------------- era state ---------------- */

  /** Era the band is currently showing (the tween's target while it runs). */
  get era(): EraId {
    return this.toEra;
  }

  get from(): EraId {
    return this.fromEra;
  }

  get progress(): number {
    return this.progressState;
  }

  get isTransitioning(): boolean {
    return this.fromEra !== this.toEra;
  }

  get isDisposed(): boolean {
    return this.disposedState;
  }

  get blendableId(): string | null {
    return this.blendableRegistration?.id ?? null;
  }

  /** `true` while the animated media walk with the frame clock. */
  get isAnimated(): boolean {
    return this.systemRegistration !== null;
  }

  /**
   * `EraBlendable`: begins a transition.
   *
   * `{ immediate: true }` (or a zero duration) snaps to the era; otherwise the
   * band cross-fades from the era it currently shows and both ends of the tween
   * are built straight away so the tween never stalls on geometry or textures.
   */
  setEra(era: EraId, options: EraTransitionOptions = {}): void {
    this.assertUsable();
    const target = assertEraId(era);
    const durationMs = options.durationMs ?? 0;

    if (options.immediate === true || durationMs <= 0) {
      this.fromEra = target;
      this.toEra = target;
      this.progressState = 1;
      this.applyMorph();
      return;
    }

    const source = this.toEra;
    this.fromEra = source;
    this.toEra = target;
    this.progressState = 0;
    for (const record of this.records.values()) {
      this.variantFor(record, source);
      this.variantFor(record, target);
    }
    this.applyMorph();
  }

  /** `EraBlendable`: one call per frame while the tween runs. */
  updateEraTransition(progress: number, transition: EraTransitionInfo): void {
    if (this.disposedState) return;
    const target = assertEraId(transition.to);
    const source = assertEraId(transition.from);
    const value = clamp01(progress);
    const complete = !transition.active || value >= 1;

    this.fromEra = complete ? target : source;
    this.toEra = target;
    this.progressState = complete ? 1 : value;
    this.applyMorph();
  }

  /** Snaps the band to an era without a tween (`setEra` with `immediate`). */
  applyEra(era: EraId): void {
    this.setEra(era, { immediate: true });
  }

  /* ---------------- content access ---------------- */

  /** The stable lot group shopfronts hang from (and register against). */
  lotObject(lotId: string): THREE.Object3D | null {
    return this.records.get(lotId)?.group ?? null;
  }

  /** The stable lot group freestanding media hang from. */
  billboardObject(lotId: string): THREE.Object3D | null {
    return this.records.get(lotId)?.billboardGroup ?? null;
  }

  /** One built `(lot, era)` variant, or `null` when it has not been built. */
  variant(lotId: string, era: EraId): StorefrontVariantHandle | null {
    return this.records.get(lotId)?.variants.get(era) ?? null;
  }

  /** Every built variant, in lot order then era order. */
  listVariants(): readonly StorefrontVariantHandle[] {
    const built: StorefrontVariantHandle[] = [];
    for (const record of this.records.values()) built.push(...record.variants.values());
    return Object.freeze(built);
  }

  /** Ids of the inspectables this API registers. */
  inspectables(): readonly string[] {
    return Object.freeze([...this.registeredIds]);
  }

  /** The plan of one `(lot, era)`, whether or not it has been built yet. */
  planFor(lotId: string, era: EraId): ShopfrontPlan | null {
    const record = this.records.get(lotId);
    if (!record) return null;
    return this.plan(record.lot, assertEraId(era));
  }

  /** The sign copy of one `(lot, era)` — the same name the info card shows. */
  shopNameFor(lotId: string, era: EraId): string | null {
    return this.planFor(lotId, era)?.shopName ?? null;
  }

  /** Advertising plans of one `(lot, era)`. */
  advertisementsFor(lotId: string, era: EraId): readonly AdvertisementPlan[] {
    const record = this.records.get(lotId);
    if (!record) return Object.freeze([]);
    return this.advertising(record.lot, this.plan(record.lot, assertEraId(era)));
  }

  /** Material keys one era resolves (at most `MAX_STOREFRONT_MATERIALS_PER_ERA`). */
  materialKeysFor(era: EraId): readonly string[] {
    return this.materialSet(assertEraId(era)).keys;
  }

  /**
   * Per-era feature totals across the whole block. Builds any variant the era is
   * missing, so the summary always describes the complete era set.
   */
  featuresFor(era: EraId): StorefrontFeatureSummary {
    const target = assertEraId(era);
    const shopfront = createShopfrontFeatureCounts();
    const ads = createAdFeatureCounts();
    const mediaProfile = createMediaProfile();
    const materialKeys = new Set<string>();
    const shopKinds = new Set<ShopKind>();
    const shopNames: string[] = [];
    const dressingKinds = new Set<ShopDressingKind>();
    const awningKinds = new Set<AwningKind>();
    const signMedia = new Set<SignMedia>();
    const adKinds = new Set<AdKind>();
    let dress = 0;
    let awnings = 0;
    let signage = 0;
    let advertising = 0;
    let billboard = 0;
    let instances = 0;
    let animatedFaces = 0;
    let glow = 0;
    let signTextureCount = 0;
    let shopfrontInstances = 0;

    for (const record of this.records.values()) {
      const variant = this.variantFor(record, target);
      addShopfrontFeatureCounts(shopfront, variant.shopfrontCounts);
      addAdFeatureCounts(ads, variant.adCounts);
      for (const className of MEDIA_CLASSES) mediaProfile[className] += variant.mediaProfile[className];
      for (const key of variant.plan.mediaProfile) signMedia.add(key);
      shopKinds.add(variant.plan.shopKind);
      shopNames.push(variant.plan.shopName);
      for (const kind of variant.plan.dressing) dressingKinds.add(kind);
      awningKinds.add(variant.plan.awning.kind);
      for (const adPlan of variant.adPlans) adKinds.add(adPlan.kind);
      for (const key of this.materialSet(target).keys) materialKeys.add(key);
      dress += variant.dressingInstances;
      awnings += variant.awningInstances;
      signage += variant.signageInstances;
      advertising += variant.advertisingInstances;
      billboard += variant.billboardInstances;
      instances += variant.instances;
      shopfrontInstances += variant.shopfrontInstances;
      animatedFaces += variant.animatedFaces;
      glow += variant.glow;
      signTextureCount += variant.signHandles.length;
    }

    return Object.freeze({
      era: target,
      lots: this.records.size,
      shopKinds: Object.freeze([...shopKinds]),
      shopNames: Object.freeze(shopNames),
      dressingKinds: Object.freeze([...dressingKinds]),
      awningKinds: Object.freeze([...awningKinds]),
      signMedia: Object.freeze([...signMedia]),
      adKinds: Object.freeze([...adKinds]),
      dressing: Object.freeze({ ...shopfront.dressingByKind }),
      shopfront: Object.freeze({ ...shopfront }),
      ads: Object.freeze({ ...ads }),
      instances,
      shopfrontInstances,
      dressingInstances: dress,
      awningInstances: awnings,
      signageInstances: signage,
      advertisingInstances: advertising,
      billboardInstances: billboard,
      mediaProfile: Object.freeze({ ...mediaProfile }),
      mediaShare: Object.freeze(shareOf(mediaProfile)),
      animatedFaces,
      glow,
      materialKeys: Object.freeze([...materialKeys]),
      signTextureCount,
    });
  }

  /** Full, read-only state of the storefront band. */
  snapshot(): StorefrontsSnapshot {
    const weights = this.currentWeights();
    const mediaProfile = createMediaProfile();
    const lots: StorefrontLotState[] = [];
    const shopNames: string[] = [];
    const materialKeys = new Set<string>();
    let visibleVariants = 0;
    let builtVariants = 0;
    let instances = 0;
    let dress = 0;
    let awnings = 0;
    let signage = 0;
    let advertising = 0;
    let billboard = 0;
    let animatedFaces = 0;
    let glow = 0;
    let shopfrontInstances = 0;

    for (const record of this.records.values()) {
      const targetPlan = this.plan(record.lot, this.toEra);
      shopNames.push(targetPlan.shopName);
      let weightSum = 0;
      let visibleCount = 0;
      let lotInstances = 0;
      let lotGlow = 0;
      let lotAnimated = 0;
      let lotShopfront = 0;

      for (const [era, variant] of record.variants) {
        builtVariants += 1;
        const weight = weights.get(era) ?? 0;
        weightSum += weight;
        if (!variant.group.visible) continue;
        visibleCount += 1;
        visibleVariants += 1;
        lotInstances += variant.instances;
        lotShopfront += variant.shopfrontInstances;
        lotGlow += variant.lastGlow * weight;
        lotAnimated += variant.animatedFaces;
        instances += variant.instances;
        dress += variant.dressingInstances;
        awnings += variant.awningInstances;
        signage += variant.signageInstances;
        advertising += variant.advertisingInstances;
        billboard += variant.billboardInstances;
        for (const className of MEDIA_CLASSES) mediaProfile[className] += variant.mediaProfile[className];
      }

      for (const key of this.materialSet(this.toEra).keys) materialKeys.add(key);

      const hasKerb = lotCarriesKerbMedia(record.lot);
      animatedFaces += lotAnimated;
      glow += lotGlow;
      shopfrontInstances += lotShopfront;
      lots.push(
        Object.freeze({
          id: record.lot.id,
          side: record.lot.side,
          landmark: record.lot.landmark === true,
          era: this.toEra,
          shopName: targetPlan.shopName,
          shopKind: targetPlan.shopKind,
          dressingKinds: targetPlan.dressing,
          awning: targetPlan.awning.kind,
          signMedia: targetPlan.signMedia,
          bladeMedia: targetPlan.bladeMedia,
          transomMedia: targetPlan.transomMedia,
          kerbMedia: targetPlan.kerbMedia,
          inspectableId: shopfrontInspectableId(record.lot.id),
          billboardInspectableId: hasKerb ? billboardInspectableId(record.lot.id) : null,
          weightSum,
          visibleVariantCount: visibleCount,
          instances: lotInstances,
          glow: lotGlow,
          animatedFaces: lotAnimated,
        }),
      );
    }

    return Object.freeze({
      version: this.version,
      era: this.toEra,
      from: this.fromEra,
      to: this.toEra,
      progress: this.progressState,
      transitioning: this.isTransitioning,
      lotCount: this.records.size,
      registeredInspectables: this.registeredIds.length,
      builtVariants,
      visibleVariants,
      shopfrontInstances,
      dressingInstances: dress,
      awningInstances: awnings,
      signageInstances: signage,
      advertisingInstances: advertising,
      billboardInstances: billboard,
      totalInstances: instances,
      mediaProfile: Object.freeze({ ...mediaProfile }),
      mediaShare: Object.freeze(shareOf(mediaProfile)),
      animatedFaces: this.animatedFacesState === 0 ? animatedFaces : this.animatedFacesState,
      glow: this.glowState === 0 ? glow : this.glowState,
      mediaPulse: this.mediaPulseState,
      tickCount: this.tickCountState,
      elapsed: this.elapsedState,
      materialCount: materialKeys.size,
      materialKeys: Object.freeze([...materialKeys]),
      signTextureCount: this.ownedHandles.length,
      shopNames: Object.freeze(shopNames),
      lots: Object.freeze(lots),
    });
  }

  /** Detaches from the timeline/context and releases everything it created. */
  dispose(): void {
    if (this.disposedState) return;
    this.disposedState = true;
    this.systemRegistration?.dispose();
    this.systemRegistration = null;
    this.blendableRegistration?.dispose();
    this.blendableRegistration = null;

    if (this.registry) {
      for (const id of this.registeredIds) this.registry.deregister(id);
    }
    this.registeredIds.length = 0;

    for (const record of this.records.values()) {
      for (const variant of record.variants.values()) variant.dispose();
      record.variants.clear();
    }
    this.plans.clear();
    this.adPlans.clear();

    for (const handle of this.ownedHandles) handle.dispose();
    this.ownedHandles.length = 0;
    this.signHandles.clear();

    this.root.removeFromParent();
    this.root.clear();

    this.geometries.dispose();
    this.releaseMaterialState();
    if (this.ownsLibrary) this.library.dispose();
  }

  /* ---------------- internals ---------------- */

  private readonly tick = (_context: SceneContext, frame: FrameInfo): void => {
    if (this.disposedState) return;
    this.tickCountState += 1;
    this.elapsedState = frame.elapsed;
    const weights = this.currentWeights();
    let animatedFaces = 0;
    let glow = 0;
    let pulse = 0;

    for (const record of this.records.values()) {
      for (const [era, variant] of record.variants) {
        const weight = weights.get(era) ?? 0;
        if (weight <= 0.01) continue;
        const state = variant.animate(frame.elapsed);
        animatedFaces += state.animatedFaces;
        glow += state.glow * weight;
        if (state.pulse > pulse) pulse = state.pulse;
      }
    }

    this.animatedFacesState = animatedFaces;
    this.glowState = glow;
    this.mediaPulseState = pulse;
  };

  private assertUsable(): void {
    if (this.disposedState) {
      throw new Error(`StorefrontsApi "${this.id}" is disposed and can no longer be driven.`);
    }
  }

  /** Cached plan for one `(lot, era)`. */
  private plan(lot: StorefrontLot, era: EraId): ShopfrontPlan {
    const key = `${lot.id}@${era}`;
    const cached = this.plans.get(key);
    if (cached) return cached;
    const planned = planShopfront(lot, era, this.random);
    this.plans.set(key, planned);
    return planned;
  }

  /** Cached advertising plans for one `(lot, era)`. */
  private advertising(lot: StorefrontLot, plan: ShopfrontPlan): readonly AdvertisementPlan[] {
    const key = `${lot.id}@${plan.era}`;
    const cached = this.adPlans.get(key);
    if (cached) return cached;
    const planned = planAdvertising(plan, this.random);
    this.adPlans.set(key, planned);
    return planned;
  }

  /** Cached shopfront material set for one era, shared across every lot. */
  private materialSet(era: EraId): StorefrontMaterialSet {
    const cached = this.materialSets.get(era);
    if (cached) return cached;
    const built = createShopfrontMaterials(this.library, era);
    this.materialSets.set(era, built);
    return built;
  }

  /** Builds (once) and returns the variant for one `(lot, era)`. */
  private variantFor(record: LotRecord, era: EraId): StorefrontVariant {
    const cached = record.variants.get(era);
    if (cached) return cached;
    const plan = this.plan(record.lot, era);
    const adPlans = this.advertising(record.lot, plan);
    const screenSpec = eraShopScreenSpec(plan);
    const variant = new StorefrontVariant({
      lot: record.lot,
      plan,
      adPlans,
      materials: this.materialSet(era),
      geometries: this.geometries,
      parent: record.group,
      random: this.random,
      fascia: this.signHandle(fasciaSpec(plan)),
      decals: this.signHandle(decalSpec(plan)),
      menu: this.signHandle(menuSpec(plan)),
      valance: plan.awning.valanceText ? this.signHandle(valanceSpec(plan)) : null,
      screen: screenSpec ? this.signHandle(screenSpec) : null,
      adMedia: adPlans.map((adPlan) => this.signHandle(advertisementSignSpec(adPlan))),
    });
    record.variants.set(era, variant);
    return variant;
  }

  /**
   * Creates (or reuses) the lit material for one sign face. Every face is a
   * canvas texture painted by the sign factory; identical specs share one handle,
   * so a billboard creative used by three lots costs one texture.
   */
  private signHandle(spec: SignFaceSpec): SignMaterialHandle {
    const key = spec.key ?? signFaceKey(spec);
    const cached = this.signHandles.get(key);
    if (cached) return cached;
    const handle = createSignMaterialHandle({
      id: key,
      handle: createSignTexture(spec, this.random),
      name: `chrono-storefront-sign-${key}`,
    });
    this.signHandles.set(key, handle);
    this.ownedHandles.push(handle);
    return handle;
  }

  /** Active cross-fade weights, keyed by era. */
  private currentWeights(): Map<EraId, number> {
    const weights = new Map<EraId, number>();
    if (this.fromEra === this.toEra) {
      weights.set(this.toEra, 1);
      return weights;
    }
    weights.set(this.fromEra, sourceEraWeight(this.progressState));
    weights.set(this.toEra, targetEraWeight(this.progressState));
    return weights;
  }

  /**
   * Pushes the morph into the scene: both eras' materials fade, both eras'
   * variants show, and every other built variant is hidden.
   */
  private applyMorph(): void {
    if (this.records.size === 0) return;
    const weights = this.currentWeights();
    const eras = new Set<EraId>([this.fromEra, this.toEra]);

    for (const [era, weight] of weights) {
      for (const material of this.materialSet(era).list) {
        // Scale the crafted opacity rather than replacing it: shop glass and
        // lightbox diffusers are deliberately translucent to begin with.
        const base = Number(material.userData.chronoBaseOpacity ?? 1);
        const opacity = clamp01(base * weight);
        material.opacity = opacity;
        material.transparent = base < 0.999 || weight < 0.995;
        material.depthWrite = opacity > 0.995;
      }
    }

    for (const record of this.records.values()) {
      for (const era of eras) {
        const variant = this.variantFor(record, era);
        variant.applyWeight(weights.get(era) ?? 0);
      }
      for (const variant of record.variants.values()) {
        if (eras.has(variant.era)) continue;
        variant.applyWeight(0);
      }
    }
  }

  /** Registers one stable inspectable per shop and per billboard lot. */
  private registerInspectables(): void {
    const registry = this.registry;
    if (!registry) return;

    for (const record of this.records.values()) {
      const shopCopy: Record<string, { name: string; blurb: string }> = {};
      const billboardCopy: Record<string, { name: string; blurb: string }> = {};
      let hasKerb = false;

      for (const era of ERA_IDS) {
        const plan = this.plan(record.lot, era);
        shopCopy[era] = {
          name: plan.shopName,
          blurb: `${plan.blurb} Signage today: ${signSentences(plan)}.`,
        };
        for (const adPlan of this.advertising(record.lot, plan)) {
          if (adPlan.slot !== 'kerb') continue;
          hasKerb = true;
          billboardCopy[era] = {
            name: `${adPlan.copy.seller} ${billboardNoun(adPlan.kind)}`,
            blurb: `“${adPlan.copy.headline}” — ${adPlan.copy.subline}. ${billboardBuildSentence(adPlan)}`,
          };
        }
      }

      const shopDefinition: InspectableDefinition = {
        id: shopfrontInspectableId(record.lot.id),
        object: record.group,
        copy: shopCopy as InspectableCopyByEra,
        label: `Shopfront (${record.lot.id})`,
        highlight: { emissive: 0xffd9a0, emissiveIntensity: 0.8 },
        data: Object.freeze({
          system: 'city-storefronts',
          kind: 'shopfront',
          lotId: record.lot.id,
          side: record.lot.side,
          frontage: record.lot.frontWidth,
          bandHeight: STOREFRONT_BAND_HEIGHT,
          eras: ERA_IDS,
        }),
      };
      registry.register(shopDefinition);
      this.registeredIds.push(shopDefinition.id);

      if (!hasKerb) continue;
      const billboardDefinition: InspectableDefinition = {
        id: billboardInspectableId(record.lot.id),
        object: record.billboardGroup,
        copy: billboardCopy as InspectableCopyByEra,
        label: `Billboard (${record.lot.id})`,
        highlight: { emissive: 0x9fdcff, emissiveIntensity: 0.85 },
        data: Object.freeze({
          system: 'city-storefronts',
          kind: 'billboard',
          lotId: record.lot.id,
          side: record.lot.side,
          eras: ERA_IDS,
        }),
      };
      registry.register(billboardDefinition);
      this.registeredIds.push(billboardDefinition.id);
    }
  }

  /** Restores shared materials to the state the rest of the app expects. */
  private releaseMaterialState(): void {
    for (const set of this.materialSets.values()) {
      for (const material of set.list) {
        const base = Number(material.userData.chronoBaseOpacity ?? 1);
        material.opacity = base;
        material.transparent = base < 0.999;
        material.depthWrite = base > 0.995;
      }
    }
    this.materialSets.clear();
  }
}

/* ------------------------------------------------------------------------- *
 * Sign-face specs
 * ------------------------------------------------------------------------- */

/** The painted fascia face of one shop. */
export function fasciaSpec(plan: ShopfrontPlan): SignFaceSpec {
  const taglines = ERA_SHOP_TAGLINES[plan.era] ?? ERA_SHOP_TAGLINES['2025'];
  const tagline = taglines[plan.shopName.length % taglines.length] as string;
  const blocks: SignTextBlock[] = [
    Object.freeze({ text: plan.shopName, role: 'title' as const }),
    Object.freeze({ text: tagline, role: 'subtitle' as const, scale: 0.13 }),
  ];
  return {
    era: plan.era,
    media: plan.signMedia,
    palette: plan.signPalette,
    blocks: Object.freeze(blocks),
    widthMeters: Math.max(2.4, plan.frontWidth - 0.72),
    heightMeters: 0.66,
    longEdge: 512,
    key: `${plan.era}:fascia:${plan.shopName}`,
    note: `fascia:${plan.shopKind}`,
  };
}

/**
 * The shared per-business poster sheet: pasted notices and price cards. The
 * face is portrait (0.5 × 0.7 m) so the writing matches the cards it lands on.
 */
export function decalSpec(plan: ShopfrontPlan): SignFaceSpec {
  const taglines = ERA_SHOP_TAGLINES[plan.era] ?? ERA_SHOP_TAGLINES['2025'];
  const blocks: SignTextBlock[] = [
    Object.freeze({ text: decalHeadline(plan), role: 'title' as const, scale: 0.2 }),
    Object.freeze({ text: plan.shopName, role: 'subtitle' as const, scale: 0.11 }),
    Object.freeze({
      text: taglines[(plan.shopName.length + 2) % taglines.length] as string,
      role: 'list' as const,
      scale: 0.07,
    }),
  ];
  return {
    era: plan.era,
    media: plan.era === '1945' || plan.era === '2005' ? 'paper' : 'print',
    palette: Object.freeze({
      board: '#efe8d8',
      ink: plan.signPalette.board.startsWith('#') ? plan.signPalette.board : '#3a3128',
      glow: plan.signPalette.trim ?? '#d9cfae',
      trim: '#b7ab90',
    }),
    blocks: Object.freeze(blocks),
    widthMeters: 0.5,
    heightMeters: 0.7,
    longEdge: 256,
    key: `${plan.era}:decal:${plan.archetype.id}`,
    border: true,
    note: `decal:${plan.shopKind}`,
  };
}

/**
 * The shared landscape sheet for chalkboards, bill boards and rack posters
 * (1.6 × 1 m), so a shop's printed pieces read at the size they are drawn.
 */
export function menuSpec(plan: ShopfrontPlan): SignFaceSpec {
  const blocks: SignTextBlock[] = [
    Object.freeze({ text: decalHeadline(plan), role: 'title' as const, scale: 0.3 }),
    Object.freeze({ text: menuPriceLine(plan), role: 'price' as const, scale: 0.2 }),
    Object.freeze({ text: plan.shopName, role: 'list' as const, scale: 0.11 }),
  ];
  return {
    era: plan.era,
    media: plan.era === '1945' || plan.era === '2005' ? 'paper' : 'print',
    palette: Object.freeze({
      board: '#141210',
      ink: '#f2ece0',
      glow: plan.signPalette.glow,
      trim: plan.signPalette.trim ?? '#d9cfae',
    }),
    blocks: Object.freeze(blocks),
    widthMeters: 1.6,
    heightMeters: 1,
    longEdge: 256,
    key: `${plan.era}:menu:${plan.archetype.id}`,
    border: true,
    note: `menu:${plan.shopKind}`,
  };
}

/**
 * The lettered awning valance of one shop: the trading name long and thin across
 * the valance, with an era tagline underneath.
 */
export function valanceSpec(plan: ShopfrontPlan): SignFaceSpec {
  const taglines = ERA_SHOP_TAGLINES[plan.era] ?? ERA_SHOP_TAGLINES['2025'];
  const tagline = taglines[(plan.shopName.length + 1) % taglines.length] as string;
  return {
    era: plan.era,
    media: plan.signMedia,
    palette: plan.signPalette,
    blocks: Object.freeze([
      Object.freeze({ text: plan.shopName, role: 'title' as const }),
      Object.freeze({ text: tagline, role: 'subtitle' as const, scale: 0.2 }),
    ]),
    widthMeters: Math.max(3, plan.frontWidth - 0.84),
    heightMeters: Math.max(0.18, plan.awning.drop),
    longEdge: 512,
    key: `${plan.era}:valance:${plan.shopName}`,
    border: false,
    note: `valance:${plan.shopKind}`,
  };
}

/** Era-appropriate price line for a menu or price board. */
export function menuPriceLine(plan: ShopfrontPlan): string {
  switch (plan.era) {
    case '1945':
      return 'BREAD 4d — SUGAR 6d — TEA 1/2';
    case '1965':
      return 'COFFEE 15c — PIE 35c — MILK 12c';
    case '1985':
      return 'PLAY 3 TOKENS $1 — TAPE HIRE $2';
    case '2005':
      return 'LATTE £2.40 — MUFFIN £1.80';
    default:
      return 'FILTER £3.20 — REFILL 40p/100g';
  }
}

function decalHeadline(plan: ShopfrontPlan): string {
  switch (plan.era) {
    case '1945':
      return 'RATION NOTICE';
    case '1965':
      return 'SPECIAL OFFER';
    case '1985':
      return 'NEW RELEASE';
    case '2005':
      return 'PRICE LIST';
    default:
      return 'TODAY’S PICKS';
  }
}

/** The era's shared dressing screen (CRT wall, video loop, LED panel). */
export function eraShopScreenSpec(plan: ShopfrontPlan): SignFaceSpec | null {
  const eraMedia = screenMediaFor(plan.era);
  if (!eraMedia) return null;
  const descriptor = plan.mediaProfile;
  const blocks: SignTextBlock[] = [
    Object.freeze({ text: screenHeadline(plan), role: 'title' as const }),
    Object.freeze({ text: 'TODAY ONLY', role: 'price' as const, scale: 0.16 }),
    Object.freeze({ text: descriptor.length > 0 ? plan.accentColor.toUpperCase() : '', role: 'list' as const, scale: 0.12 }),
  ];
  return {
    era: plan.era,
    media: eraMedia,
    palette: Object.freeze({
      board: '#0b0d14',
      ink: plan.glowColor,
      glow: plan.glowColor,
      trim: '#20242e',
    }),
    blocks: Object.freeze(blocks),
    widthMeters: 1.6,
    heightMeters: 1,
    longEdge: 384,
    key: `${plan.era}:screen`,
    border: false,
    note: 'dressing-screen',
  };
}

function screenMediaFor(era: EraId): SignMedia | null {
  switch (era) {
    case '1965':
      return 'backlit';
    case '1985':
    case '2005':
      return 'video';
    case '2025':
      return 'led';
    default:
      return null;
  }
}

function screenHeadline(plan: ShopfrontPlan): string {
  switch (plan.era) {
    case '1965':
      return 'TODAY’S SPECIAL';
    case '1985':
      return 'PLAY NOW';
    case '2005':
      return 'CONNECTED';
    default:
      return 'LIVE NOW';
  }
}

/* ------------------------------------------------------------------------- *
 * Copy helpers
 * ------------------------------------------------------------------------- */

/** Phrase describing the media a plan actually shows. */
export function signSentences(plan: ShopfrontPlan): string {
  const classes = new Set<MediaClass>();
  for (const media of plan.mediaProfile) classes.add(mediaClass(media));
  const phrases = [...classes].filter((entry) => entry !== 'print').map(describeMedia);
  const animated = [...classes].some(isEmissiveClass);
  const body = phrases.length > 0 ? phrases.join(', ') : 'unlit painted boards';
  return animated ? `${body}, lit and animating with the hour` : `${body}, none of it lit`;
}

/** Noun for a freestanding media structure. */
export function billboardNoun(kind: AdKind): string {
  switch (kind) {
    case 'paperHoard':
      return 'hoarding';
    case 'hologramColumn':
      return 'hologram column';
    case 'videoBillboard':
      return 'video billboard';
    case 'ledBillboard':
      return 'LED billboard';
    case 'backlitBillboard':
      return 'backlit billboard';
    case 'busShelterPoster':
      return 'bus-shelter poster';
    default:
      return 'billboard';
  }
}

/** Sentence describing how a billboard is lit, for the info card. */
export function billboardBuildSentence(plan: AdvertisementPlan): string {
  const technology = describeMedia(mediaClass(plan.media));
  const motion = plan.animated ? 'The creative walks a looping reel.' : 'The creative is a single printed sheet.';
  const place =
    plan.slot === 'kerb'
      ? 'It stands on the sidewalk clear of the shopfront band.'
      : 'It hangs within the 4 m shopfront band.';
  return `This ${billboardNoun(plan.kind)} is built from ${technology}. ${motion} ${place}`;
}

function shareOf(profile: Record<MediaClass, number>): Record<MediaClass, number> {
  let total = 0;
  for (const className of MEDIA_CLASSES) total += profile[className];
  const share = createMediaProfile();
  if (total <= 0) return share;
  for (const className of MEDIA_CLASSES) share[className] = profile[className] / total;
  return share;
}

/**
 * Builds the block's era-evolving storefront band.
 *
 * ```ts
 * const storefronts = createStorefrontsApi({ context, timeline, registry });
 * context.tick(0.1);                     // storefronts follow the timeline
 * storefronts.featuresFor('1985').shopNames;
 * ```
 */
export function createStorefrontsApi(options: StorefrontsApiOptions): StorefrontsApi {
  return new StorefrontsApi(options);
}

/** The shop archetypes one era offers, re-exported for HUDs and tests. */
export { getShopArchetypes, MAX_STOREFRONT_MATERIALS_PER_ERA };
