"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.resolvePaletteColor = exports.PALETTE_CSS_VARS = exports.PALETTE_FALLBACK = exports.buildingDepthKey = exports.sortBuildingsForDraw = exports.Renderer = exports.GameLoop = exports.DEFAULT_CAMERA_CONFIG = exports.Camera = void 0;
var Camera_1 = require("./Camera");
Object.defineProperty(exports, "Camera", { enumerable: true, get: function () { return Camera_1.Camera; } });
Object.defineProperty(exports, "DEFAULT_CAMERA_CONFIG", { enumerable: true, get: function () { return Camera_1.DEFAULT_CAMERA_CONFIG; } });
var GameLoop_1 = require("./GameLoop");
Object.defineProperty(exports, "GameLoop", { enumerable: true, get: function () { return GameLoop_1.GameLoop; } });
var Renderer_1 = require("./Renderer");
Object.defineProperty(exports, "Renderer", { enumerable: true, get: function () { return Renderer_1.Renderer; } });
Object.defineProperty(exports, "sortBuildingsForDraw", { enumerable: true, get: function () { return Renderer_1.sortBuildingsForDraw; } });
Object.defineProperty(exports, "buildingDepthKey", { enumerable: true, get: function () { return Renderer_1.buildingDepthKey; } });
var palette_1 = require("./palette");
Object.defineProperty(exports, "PALETTE_FALLBACK", { enumerable: true, get: function () { return palette_1.PALETTE_FALLBACK; } });
Object.defineProperty(exports, "PALETTE_CSS_VARS", { enumerable: true, get: function () { return palette_1.PALETTE_CSS_VARS; } });
Object.defineProperty(exports, "resolvePaletteColor", { enumerable: true, get: function () { return palette_1.resolvePaletteColor; } });
