/**
 * The five Chrono City eras.
 *
 * Every field is deliberately period-plausible and *mutually distinct* across
 * the five years: facade palettes, vehicle archetypes, storefront names,
 * advertisement copy/format, outfit swatches and street furniture all differ so
 * the transformation is unmistakable. Content completeness and cross-era
 * distinctness are asserted by `tests/eras.test.ts` and
 * `tests/eraContent.test.ts`.
 */

import { ERA_AUDIO } from '../audio/eraAudio';
import { YEARS, type EraDefinition, type Year } from './types';

export const ERAS: Record<Year, EraDefinition> = {
  1945: {
    year: 1945,
    title: '1945 · Victory Over Broadway',
    tagline: 'Wartime hush, streetcar bells and painted brick promises.',
    facts: [
      'Tram rails still run down the centre of both streets.',
      'Brick walls carry hand-painted war-bond and rationing ads.',
      'Fedoras, day-dresses and demob suits crowd the sidewalk.',
      'Rooftop water towers supply most of the block.',
      'Streetlamps are still incandescent globes.',
    ],
    palette: {
      skyTop: '#7d6b52',
      skyBottom: '#d9b98a',
      fog: '#c2a882',
      fogDensity: 0.0042,
      sun: '#ffd9a0',
      sunPosition: [-70, 34, -58],
      sunIntensity: 1.7,
      ambient: '#6b5a45',
      ambientIntensity: 0.42,
      hemiSky: '#a08a6a',
      hemiGround: '#3a2f22',
      hemiIntensity: 0.55,
      horizon: '#e8b878',
      clarity: 0.45,
    },
    grade: { lift: 0.07, saturation: 0.72, gamma: 1.06, temperature: 0.42, grain: 0.6, vignette: 0.55, bloom: 0.3 },
    architecture: {
      styles: ['art-deco', 'brick', 'brownstone', 'stucco'],
      facadeColors: ['#8a5a44', '#a9795a', '#7d6a5a', '#b9a48b', '#6f4f3d', '#96705a'],
      minFloors: 3,
      maxFloors: 9,
      windowStyle: 'sash',
      setbacks: true,
      waterTowers: true,
      fireEscapes: true,
      roofAc: false,
      antennas: true,
      satelliteDishes: false,
      roofBillboards: false,
      glassRatio: 0.08,
    },
    vehicles: [
      { id: '1945-sedan', kind: 'sedan', label: 'Rounded sedan', count: 5, length: 4.9, width: 1.9, height: 1.8, body: '#25313f', accent: '#b9a281', movingRatio: 0.7, engineHz: 74 },
      { id: '1945-taxi', kind: 'taxi', label: 'Checker taxicab', count: 2, length: 5.1, width: 2, height: 1.95, body: '#8f2f2a', accent: '#e6d8bd', movingRatio: 0.6, engineHz: 78 },
      { id: '1945-truck', kind: 'truck', label: 'Flatbed delivery truck', count: 2, length: 6.4, width: 2.3, height: 2.9, body: '#4a4f42', accent: '#8a7a5a', movingRatio: 0.8, engineHz: 58 },
      { id: '1945-streetcar', kind: 'streetcar', label: 'Peter Witt streetcar', count: 2, length: 13.5, width: 2.6, height: 3.6, body: '#7a2f34', accent: '#d9c7a8', movingRatio: 1, engineHz: 62 },
      { id: '1945-bus', kind: 'bus', label: 'Twin Coach city bus', count: 2, length: 9.2, width: 2.5, height: 3, body: '#3f5a4a', accent: '#c9c0a4', movingRatio: 0.9, engineHz: 66 },
      { id: '1945-bicycle', kind: 'bicycle', label: 'Delivery bicycle', count: 6, length: 1.9, width: 0.6, height: 1.3, body: '#2f3a44', accent: '#b08a4a', movingRatio: 0.6, engineHz: 0 },
    ],
    storefronts: [
      { id: '1945-grocery', name: "Harlan's Grocery", category: 'grocer', awning: '#4a5a3e', display: 'FRESH EGGS · RATION BOOKS HONOURED', signFormat: 'painted', signColor: '#e6d8bd', glassTint: '#6f7a6a' },
      { id: '1945-diner', name: 'Victory Diner', category: 'diner', awning: '#7a2f34', display: 'BLUE PLATE 35¢ · PIE & COFFEE', signFormat: 'painted', signColor: '#f0e4c8', glassTint: '#7d7263' },
      { id: '1945-hardware', name: 'Miller & Sons Hardware', category: 'hardware', awning: '#4a4f42', display: 'TOOLS · PAINT · GALVANISED BUCKETS', signFormat: 'poster', signColor: '#d9c7a8', glassTint: '#6a6f66' },
      { id: '1945-tailor', name: 'Rosewood Tailors', category: 'tailor', awning: '#3d4a63', display: 'SUITS PRESSED WHILE YOU WAIT', signFormat: 'painted', signColor: '#e0d6bf', glassTint: '#6d7480' },
      { id: '1945-bakery', name: 'Bluebird Bakery', category: 'bakery', awning: '#5a6f8a', display: 'BREAD · CAKES · WEDDING ORDERS', signFormat: 'poster', signColor: '#f2e8d0', glassTint: '#7a7f86' },
    ],
    advertisements: [
      { id: '1945-bonds', copy: 'BUY WAR BONDS — VICTORY IS OUR BUSINESS', format: 'painted', colors: ['#8a2f2a', '#e6d8bd'], placement: 'wall', emissive: false, scrolling: false },
      { id: '1945-tea', copy: 'LIPTON TEA — FRESH AS DAWN', format: 'painted', colors: ['#2f4a63', '#e8dcc2'], placement: 'wall', emissive: false, scrolling: false },
      { id: '1945-land-army', copy: "JOIN THE WOMEN'S LAND ARMY", format: 'poster', colors: ['#3f5a3a', '#f0e6cf'], placement: 'wall', emissive: false, scrolling: false },
      { id: '1945-scrap', copy: 'SAVE SCRAP METAL FOR THE FRONT', format: 'painted', colors: ['#6f4f3d', '#e0cfae'], placement: 'rooftop', emissive: false, scrolling: false },
    ],
    outfits: [
      { id: '1945-factory', label: 'Factory worker', colors: ['#4a5a3e', '#6b6f5a', '#2f2a24'], skin: '#c99a72', accessory: 'fedora', accessoryColor: '#3a3226', hem: 0.62, silhouette: 'long-coat' },
      { id: '1945-clerk', label: 'Office clerk', colors: ['#3d4a63', '#8c8375', '#2a2c33'], skin: '#8f6244', accessory: 'suit', accessoryColor: '#5a4632', hem: 0.55, silhouette: 'wide-lapel-suit' },
      { id: '1945-homemaker', label: 'Homemaker', colors: ['#a7566a', '#d9c7a8', '#5a3a3f'], skin: '#e2b58c', accessory: 'day-dress', accessoryColor: '#e6d8bd', hem: 0.7, silhouette: 'fitted-dress' },
      { id: '1945-newsboy', label: 'Newsboy', colors: ['#8a7a4f', '#4a4136', '#c9b48a'], skin: '#d5a172', accessory: 'pillbox-hat', accessoryColor: '#6b5a3a', hem: 0.5, silhouette: 'athletic' },
      { id: '1945-nurse', label: 'Nurse', colors: ['#e3e0d6', '#b9b3a4', '#7a7468'], skin: '#b8805a', accessory: 'hat', accessoryColor: '#f2efe6', hem: 0.66, silhouette: 'fitted-dress' },
      { id: '1945-seaman', label: 'Seaman on leave', colors: ['#2f3f5e', '#e8e5da', '#3a4660'], skin: '#e8c39e', accessory: 'overcoat', accessoryColor: '#1f2a3d', hem: 0.6, silhouette: 'long-coat' },
    ],
    props: {
      lampStyle: 'incandescent-globe',
      lampColor: '#ffd9a0',
      transit: 'streetcar',
      telephonePoles: true,
      tramRails: true,
      bikeLane: false,
      newsstands: true,
      newspaperBoxes: true,
      busStopShelter: false,
      hydrantColor: '#8a2f2a',
      benches: 6,
      planters: 2,
    },
    audio: ERA_AUDIO[1945],
    bannerText: 'BUY WAR BONDS — KEEP THEM FLYING',
    birds: 7,
    trafficSpeed: 0.55,
    crowdPace: 0.62,
  },

  1965: {
    year: 1965,
    title: '1965 · Mid-Century Boom',
    tagline: 'Chrome, neon and rocket-age optimism on every corner.',
    facts: [
      'The first neon diner signs buzz along the shopfronts.',
      'V8 muscle cars idle beside sensible new compacts.',
      'Swiss-mod dresses and slim-lapel suits fill the sidewalk.',
      'Rooftop billboards advertise drive-ins and cola.',
      'Swan-neck lamps replaced the old globes.',
    ],
    palette: {
      skyTop: '#3f76b5',
      skyBottom: '#e8c9a0',
      fog: '#a8bccb',
      fogDensity: 0.0031,
      sun: '#fff0c8',
      sunPosition: [58, 46, -30],
      sunIntensity: 2.15,
      ambient: '#6f8199',
      ambientIntensity: 0.5,
      hemiSky: '#88a8cc',
      hemiGround: '#4a4034',
      hemiIntensity: 0.62,
      horizon: '#f6d9a8',
      clarity: 0.75,
    },
    grade: { lift: 0.035, saturation: 1.06, gamma: 0.99, temperature: 0.12, grain: 0.34, vignette: 0.4, bloom: 0.6 },
    architecture: {
      styles: ['mid-century', 'brick', 'stucco', 'concrete'],
      facadeColors: ['#c9b79c', '#e0d3b8', '#a8b6a0', '#d8c2a0', '#9fb4b8', '#c2a98a'],
      minFloors: 4,
      maxFloors: 12,
      windowStyle: 'awning',
      setbacks: false,
      waterTowers: true,
      fireEscapes: true,
      roofAc: true,
      antennas: true,
      satelliteDishes: false,
      roofBillboards: true,
      glassRatio: 0.28,
    },
    vehicles: [
      { id: '1965-muscle', kind: 'muscle-car', label: 'Muscle car', count: 3, length: 5.2, width: 2, height: 1.5, body: '#b0342f', accent: '#e8e2d2', movingRatio: 0.8, engineHz: 86 },
      { id: '1965-wagon', kind: 'station-wagon', label: 'Family station wagon', count: 3, length: 5.5, width: 2.05, height: 1.65, body: '#4a7f7a', accent: '#ddd6c2', movingRatio: 0.6, engineHz: 82 },
      { id: '1965-compact', kind: 'compact', label: 'Economy compact', count: 4, length: 4.2, width: 1.8, height: 1.45, body: '#d9b84a', accent: '#3a3a3a', movingRatio: 0.6, engineHz: 98 },
      { id: '1965-taxi', kind: 'taxi', label: 'Checker cab', count: 2, length: 5.2, width: 2, height: 1.6, body: '#2f7f5f', accent: '#f0e8d0', movingRatio: 0.7, engineHz: 84 },
      { id: '1965-bus', kind: 'bus', label: 'Rocket-era city bus', count: 2, length: 10, width: 2.55, height: 3, body: '#3f6fa8', accent: '#e8e4d6', movingRatio: 0.9, engineHz: 70 },
      { id: '1965-bicycle', kind: 'bicycle', label: 'Cruiser bicycle', count: 5, length: 1.9, width: 0.6, height: 1.25, body: '#2f6f8f', accent: '#d9c070', movingRatio: 0.55, engineHz: 0 },
    ],
    storefronts: [
      { id: '1965-diner', name: 'Galaxy Diner', category: 'diner', awning: '#2f6fa8', display: 'OPEN ALL NIGHT · SHAKES & FRIES', signFormat: 'neon', signColor: '#5fe0ff', glassTint: '#6d8496' },
      { id: '1965-records', name: 'Atomic Records', category: 'records', awning: '#c93f5a', display: 'NEW RELEASES EVERY FRIDAY', signFormat: 'neon', signColor: '#ff6fa8', glassTint: '#6f6a80' },
      { id: '1965-motors', name: 'Continental Motors', category: 'auto', awning: '#3f5a8a', display: 'TUNE-UP · WHITEWALL TYRES', signFormat: 'painted', signColor: '#f0ead4', glassTint: '#727a84' },
      { id: '1965-salon', name: 'Sunbeam Salon', category: 'beauty', awning: '#d9a83f', display: 'BOUFFANTS · PERMANENTS · TINTS', signFormat: 'neon', signColor: '#ffe07a', glassTint: '#8a8078' },
      { id: '1965-cleaners', name: 'Rocket Cleaners', category: 'cleaners', awning: '#4a8a7a', display: 'ONE HOUR MARTINISING', signFormat: 'painted', signColor: '#e8f0e0', glassTint: '#7a8a86' },
    ],
    advertisements: [
      { id: '1965-cola', copy: 'TINGLE COLA — THE MODERN TASTE', format: 'neon', colors: ['#ff4f6f', '#ffe07a'], placement: 'storefront', emissive: true, scrolling: false },
      { id: '1965-diner-neon', copy: 'EAT AT GALAXY — OPEN ALL NIGHT', format: 'neon', colors: ['#5fe0ff', '#ff6fa8'], placement: 'facade', emissive: true, scrolling: false },
      { id: '1965-drive-in', copy: 'DRIVE-IN TONIGHT: DOUBLE FEATURE', format: 'poster', colors: ['#c93f5a', '#f2e4c4'], placement: 'rooftop', emissive: false, scrolling: false },
    ],
    outfits: [
      { id: '1965-secretary', label: 'Secretary', colors: ['#c46a8a', '#f0e4c8', '#6a4450'], skin: '#e8c09a', accessory: 'pillbox-hat', accessoryColor: '#d94f8a', hem: 0.62, silhouette: 'fitted-dress' },
      { id: '1965-adman', label: 'Madison Avenue exec', colors: ['#4a5a7a', '#dfe3e8', '#2f3a4d'], skin: '#c98f66', accessory: 'suit', accessoryColor: '#8a2f3f', hem: 0.54, silhouette: 'wide-lapel-suit' },
      { id: '1965-beatnik', label: 'Beat poet', colors: ['#2b2b2b', '#6a3f2f', '#c9c2b4'], skin: '#8a5f40', accessory: 'sunglasses', accessoryColor: '#1a1a1a', hem: 0.58, silhouette: 'long-coat' },
      { id: '1965-surfer', label: 'Surfer', colors: ['#e0a33f', '#2f7fa0', '#f2e3c2'], skin: '#d9a271', accessory: 'sunglasses', accessoryColor: '#2f5f7a', hem: 0.45, silhouette: 'athletic' },
      { id: '1965-student', label: 'College student', colors: ['#7a9a5a', '#e6dfc6', '#4a5a3a'], skin: '#b8805a', accessory: 'backpack', accessoryColor: '#6a5a3a', hem: 0.5, silhouette: 'athletic' },
      { id: '1965-salesman', label: 'Travelling salesman', colors: ['#8a6a3f', '#d8c9a8', '#4a3a25'], skin: '#e0b98e', accessory: 'fedora', accessoryColor: '#4a3a25', hem: 0.56, silhouette: 'wide-lapel-suit' },
    ],
    props: {
      lampStyle: 'swan-neck',
      lampColor: '#fff0c0',
      transit: 'trolleybus',
      telephonePoles: true,
      tramRails: true,
      bikeLane: false,
      newsstands: true,
      newspaperBoxes: true,
      busStopShelter: false,
      hydrantColor: '#c94a2f',
      benches: 5,
      planters: 3,
    },
    audio: ERA_AUDIO[1965],
    bannerText: 'TINGLE COLA — THE MODERN TASTE',
    birds: 5,
    trafficSpeed: 0.78,
    crowdPace: 0.78,
  },

  1985: {
    year: 1985,
    title: '1985 · Neon Downtown',
    tagline: 'Glass infill, arcades and synth spilling out of boom boxes.',
    facts: [
      'Glass-and-steel infill towers push above the old brick.',
      'Rooftop billboards and arcade neon light the street.',
      'Boxy sedans, vans and the first hatchbacks jam the lanes.',
      'Bell-bottoms, shoulder pads and leather jackets everywhere.',
      'Satellite dishes appeared on the older roofs.',
    ],
    palette: {
      skyTop: '#26265c',
      skyBottom: '#ff8a5c',
      fog: '#4a3f63',
      fogDensity: 0.0036,
      sun: '#ff9a63',
      sunPosition: [-52, 26, 66],
      sunIntensity: 1.55,
      ambient: '#5b4a72',
      ambientIntensity: 0.46,
      hemiSky: '#7a4f8a',
      hemiGround: '#241f30',
      hemiIntensity: 0.5,
      horizon: '#ff6f9a',
      clarity: 0.6,
    },
    grade: { lift: 0.05, saturation: 1.24, gamma: 1.02, temperature: -0.14, grain: 0.3, vignette: 0.5, bloom: 1.05 },
    architecture: {
      styles: ['glass-steel', 'concrete', 'brick', 'mid-century'],
      facadeColors: ['#5c6470', '#7a8390', '#8f8a7a', '#6b7280', '#95908a', '#4f5766'],
      minFloors: 6,
      maxFloors: 20,
      windowStyle: 'ribbon',
      setbacks: false,
      waterTowers: false,
      fireEscapes: false,
      roofAc: true,
      antennas: true,
      satelliteDishes: true,
      roofBillboards: true,
      glassRatio: 0.52,
    },
    vehicles: [
      { id: '1985-sedan', kind: 'sedan', label: 'Boxy sedan', count: 4, length: 5, width: 1.95, height: 1.45, body: '#8a3f4f', accent: '#c9c4b8', movingRatio: 0.7, engineHz: 104 },
      { id: '1985-van', kind: 'van', label: 'Conversion van', count: 3, length: 5.6, width: 2.1, height: 2.3, body: '#3f5a8a', accent: '#e0d8c4', movingRatio: 0.6, engineHz: 92 },
      { id: '1985-hatchback', kind: 'hatchback', label: 'Early hatchback', count: 4, length: 4, width: 1.75, height: 1.4, body: '#d9d2c0', accent: '#4a4a52', movingRatio: 0.65, engineHz: 116 },
      { id: '1985-taxi', kind: 'taxi', label: 'Boxy cab', count: 3, length: 5.1, width: 1.95, height: 1.5, body: '#d9a52f', accent: '#2f2f2f', movingRatio: 0.75, engineHz: 100 },
      { id: '1985-truck', kind: 'truck', label: 'Box delivery truck', count: 2, length: 6.8, width: 2.3, height: 3.1, body: '#6f6a5f', accent: '#c93f2f', movingRatio: 0.7, engineHz: 76 },
      { id: '1985-bicycle', kind: 'bicycle', label: 'BMX bicycle', count: 4, length: 1.8, width: 0.62, height: 1.2, body: '#c93f2f', accent: '#e0e0e0', movingRatio: 0.5, engineHz: 0 },
    ],
    storefronts: [
      { id: '1985-video', name: 'Video Vault', category: 'video', awning: '#3f3f8a', display: 'NEW RELEASES · 2 FOR 1 TUESDAYS', signFormat: 'neon', signColor: '#ff4fd9', glassTint: '#5a5a86' },
      { id: '1985-noodle', name: 'Neon Noodle House', category: 'restaurant', awning: '#8a2f5a', display: 'OPEN TIL 3 AM · NOODLES & TEA', signFormat: 'neon', signColor: '#ff8a3f', glassTint: '#7a5a6a' },
      { id: '1985-records', name: 'Pirate Radio Records', category: 'records', awning: '#2f8a7a', display: 'IMPORTS · 12" SINGLES · TAPES', signFormat: 'ticker', signColor: '#3fffd0', glassTint: '#5f8a86' },
      { id: '1985-cassette', name: 'Cassette Corner', category: 'electronics', awning: '#5a5a5f', display: 'PORTABLE STEREOS · BLANK TAPE', signFormat: 'neon', signColor: '#6fd0ff', glassTint: '#6a6a74' },
      { id: '1985-burger', name: 'Sizzle Burger', category: 'fast-food', awning: '#c93f2f', display: 'DRIVE-THRU OPEN LATE', signFormat: 'billboard', signColor: '#ffe07a', glassTint: '#8a7266' },
    ],
    advertisements: [
      { id: '1985-arcade', copy: 'ARCADIA ARCADE — TWO TOKENS A PLAY', format: 'neon', colors: ['#ff3f8a', '#3fffd0'], placement: 'storefront', emissive: true, scrolling: false },
      { id: '1985-cola', copy: 'CHROME COLA — TASTE THE FUTURE', format: 'ticker', colors: ['#ff8a3f', '#e0e0e0'], placement: 'rooftop', emissive: true, scrolling: true },
      { id: '1985-movie', copy: 'NIGHT RIDER — FRIDAY AT THE MULTIPLEX', format: 'billboard', colors: ['#c93f5a', '#7a3fd9'], placement: 'rooftop', emissive: false, scrolling: false },
    ],
    outfits: [
      { id: '1985-punk', label: 'Punk kid', colors: ['#1f1f22', '#c02030', '#6a6a70'], skin: '#dcae8a', accessory: 'denim-jacket', accessoryColor: '#4a5a7a', hem: 0.6, silhouette: 'bell-bottom' },
      { id: '1985-shopper', label: 'Mall shopper', colors: ['#e05a9a', '#f2e6dc', '#3fa0c9'], skin: '#e8c8a8', accessory: 'shoulder-pads', accessoryColor: '#3fa0c9', hem: 0.52, silhouette: 'athletic' },
      { id: '1985-broker', label: 'Wall Street broker', colors: ['#3a3f4a', '#d6d2c4', '#8a2f3f'], skin: '#c98f66', accessory: 'suit', accessoryColor: '#8a2f3f', hem: 0.56, silhouette: 'wide-lapel-suit' },
      { id: '1985-aerobics', label: 'Aerobics instructor', colors: ['#39d0b0', '#ff5fa0', '#22262e'], skin: '#b8805a', accessory: 'headband', accessoryColor: '#ff5fa0', hem: 0.46, silhouette: 'athletic' },
      { id: '1985-newwave', label: 'New-wave clubber', colors: ['#5a2f8a', '#2fd0e0', '#e8e4f0'], skin: '#8a5f40', accessory: 'sunglasses', accessoryColor: '#2f2f3a', hem: 0.58, silhouette: 'bell-bottom' },
      { id: '1985-cabbie', label: 'Cabbie', colors: ['#6a5a3f', '#c9b48a', '#3a3226'], skin: '#e0b98e', accessory: 'hat', accessoryColor: '#3a3226', hem: 0.6, silhouette: 'long-coat' },
    ],
    props: {
      lampStyle: 'sodium-cobra',
      lampColor: '#ffb060',
      transit: 'bus',
      telephonePoles: true,
      tramRails: false,
      bikeLane: false,
      newsstands: true,
      newspaperBoxes: true,
      busStopShelter: true,
      hydrantColor: '#c92f2f',
      benches: 5,
      planters: 3,
    },
    audio: ERA_AUDIO[1985],
    bannerText: 'CHROME COLA — TASTE THE FUTURE',
    birds: 3,
    trafficSpeed: 0.95,
    crowdPace: 0.95,
  },

  2005: {
    year: 2005,
    title: '2005 · Millennium Mall',
    tagline: 'Screens on every wall, SUVs idling on free Wi-Fi corner.',
    facts: [
      'LED digital billboards replaced the painted and neon boards.',
      'SUVs and fleet sedans dominate, with bike racks returning.',
      'Chain-store facades and bus shelters line the sidewalk.',
      'Low-rise jeans, messenger bags and flip phones everywhere.',
      'Curtain-wall glass towers shadow the last brick walk-ups.',
    ],
    palette: {
      skyTop: '#1b3a63',
      skyBottom: '#9fc4d8',
      fog: '#7f93a6',
      fogDensity: 0.0028,
      sun: '#ffffff',
      sunPosition: [36, 62, 22],
      sunIntensity: 2.3,
      ambient: '#7f93a6',
      ambientIntensity: 0.55,
      hemiSky: '#93b4cc',
      hemiGround: '#5a5f66',
      hemiIntensity: 0.66,
      horizon: '#cfe0ea',
      clarity: 0.85,
    },
    grade: { lift: 0.025, saturation: 1.08, gamma: 0.98, temperature: -0.08, grain: 0.18, vignette: 0.34, bloom: 0.75 },
    architecture: {
      styles: ['glass-steel', 'glass-tower', 'concrete', 'brick'],
      facadeColors: ['#b9c6d2', '#8fa3b5', '#d5dde3', '#6f8496', '#aebfcb', '#cfd8de'],
      minFloors: 8,
      maxFloors: 26,
      windowStyle: 'curtain-wall',
      setbacks: true,
      waterTowers: false,
      fireEscapes: false,
      roofAc: true,
      antennas: true,
      satelliteDishes: true,
      roofBillboards: true,
      glassRatio: 0.68,
    },
    vehicles: [
      { id: '2005-suv', kind: 'suv', label: 'Full-size SUV', count: 5, length: 5.4, width: 2.1, height: 2, body: '#2f3a4a', accent: '#c9ccd2', movingRatio: 0.7, engineHz: 82 },
      { id: '2005-sedan', kind: 'sedan', label: 'Fleet sedan', count: 4, length: 4.9, width: 1.9, height: 1.45, body: '#8f9aa6', accent: '#3a4048', movingRatio: 0.7, engineHz: 96 },
      { id: '2005-truck', kind: 'truck', label: 'Box delivery truck', count: 2, length: 7, width: 2.35, height: 3.2, body: '#d5d8dc', accent: '#2f6fa8', movingRatio: 0.75, engineHz: 74 },
      { id: '2005-bus', kind: 'bus', label: 'Low-floor city bus', count: 2, length: 11, width: 2.6, height: 3.1, body: '#c9cdd2', accent: '#2f8fa8', movingRatio: 0.9, engineHz: 68 },
      { id: '2005-taxi', kind: 'taxi', label: 'Medallion taxi', count: 3, length: 5, width: 1.95, height: 1.55, body: '#e0a83f', accent: '#2f2f2f', movingRatio: 0.8, engineHz: 94 },
      { id: '2005-bicycle', kind: 'bicycle', label: 'Aluminium commuter bike', count: 3, length: 1.8, width: 0.6, height: 1.2, body: '#3f8f6f', accent: '#e0e0e0', movingRatio: 0.5, engineHz: 0 },
    ],
    storefronts: [
      { id: '2005-games', name: 'Pixel Palace Games', category: 'games', awning: '#2f4a8a', display: 'MIDNIGHT LAUNCH · TRADE-INS', signFormat: 'led', signColor: '#6fd0ff', glassTint: '#5f6a86' },
      { id: '2005-coffee', name: 'Bean There Coffee', category: 'coffee', awning: '#4a3f33', display: 'FREE WI-FI · FAIR TRADE', signFormat: 'led', signColor: '#ffe0a8', glassTint: '#6a6258' },
      { id: '2005-pharmacy', name: 'Northgate Pharmacy', category: 'pharmacy', awning: '#2f8f7a', display: '24 HOUR PHARMACY · PHOTOS', signFormat: 'neon', signColor: '#5fffa8', glassTint: '#728a86' },
      { id: '2005-sports', name: 'Summit Sporting Goods', category: 'sports', awning: '#c95a2f', display: 'RUNNING · CLIMBING · TEAM KIT', signFormat: 'billboard', signColor: '#ffffff', glassTint: '#8a7a72' },
      { id: '2005-nails', name: 'Zen Nail Bar', category: 'beauty', awning: '#8a4f8a', display: 'WALK-INS WELCOME · GEL & SPA', signFormat: 'neon', signColor: '#ff8ad0', glassTint: '#7a6a84' },
    ],
    advertisements: [
      { id: '2005-phones', copy: 'HALO PHONES — UNLIMITED TALK, FREE NIGHTS', format: 'led', colors: ['#2f6fa8', '#e8f4ff'], placement: 'rooftop', emissive: true, scrolling: false },
      { id: '2005-launch', copy: 'PIXEL PALACE — MIDNIGHT LAUNCH PARTY', format: 'billboard', colors: ['#c93f2f', '#ffe07a'], placement: 'wall', emissive: false, scrolling: false },
      { id: '2005-wifi', copy: 'BEAN THERE — FREE WI-FI, ALL DAY', format: 'neon', colors: ['#5fffa8', '#ffe0a8'], placement: 'storefront', emissive: true, scrolling: false },
    ],
    outfits: [
      { id: '2005-teen', label: 'Teen texter', colors: ['#3f6fbf', '#e8e4d8', '#d8d2c2'], skin: '#e0b48c', accessory: 'phone', accessoryColor: '#3a3f4a', hem: 0.5, silhouette: 'athletic' },
      { id: '2005-commuter', label: 'Office commuter', colors: ['#4a4a4f', '#b8bcc4', '#2f3238'], skin: '#c98f66', accessory: 'phone', accessoryColor: '#5a5f66', hem: 0.52, silhouette: 'athletic' },
      { id: '2005-student', label: 'High-school student', colors: ['#c94a3a', '#f0eee6', '#5a5a5f'], skin: '#8a5f40', accessory: 'backpack', accessoryColor: '#3f4a5a', hem: 0.48, silhouette: 'athletic' },
      { id: '2005-corporate', label: 'Corporate analyst', colors: ['#6a7a8a', '#e0dcd2', '#3a4450'], skin: '#b8805a', accessory: 'suit', accessoryColor: '#3a4450', hem: 0.56, silhouette: 'wide-lapel-suit' },
      { id: '2005-athleisure', label: 'Yoga mom', colors: ['#e0a0c0', '#d8d4e0', '#8a8aa0'], skin: '#e8c8a8', accessory: 'none', accessoryColor: '#d8d4e0', hem: 0.46, silhouette: 'athletic' },
      { id: '2005-skater', label: 'Skater', colors: ['#2f2f33', '#8a3f2f', '#c9c4b8'], skin: '#dcae8a', accessory: 'sunglasses', accessoryColor: '#22262b', hem: 0.54, silhouette: 'athletic' },
    ],
    props: {
      lampStyle: 'led-slim',
      lampColor: '#fff6e0',
      transit: 'bus',
      telephonePoles: false,
      tramRails: false,
      bikeLane: false,
      newsstands: false,
      newspaperBoxes: true,
      busStopShelter: true,
      hydrantColor: '#d9d9d9',
      benches: 7,
      planters: 5,
    },
    audio: ERA_AUDIO[2005],
    bannerText: 'HALO PHONES — UNLIMITED TALK',
    birds: 4,
    trafficSpeed: 1.1,
    crowdPace: 1.08,
  },

  2025: {
    year: 2025,
    title: '2025 · Green Circuit',
    tagline: 'EVs hum past LED façades while the bike lane runs bright.',
    facts: [
      'LED media facades wrap the newest towers in moving light.',
      'EVs, rideshare sedans, cargo bikes and e-scooters share the road.',
      'A protected green bike lane runs down both streets.',
      'Rooftop gardens and solar arrays replaced the old water tanks.',
      'Streetwear, tech-wear hoodies and phones-in-hand crowds.',
    ],
    palette: {
      skyTop: '#101d3a',
      skyBottom: '#7fa8c9',
      fog: '#5f7a93',
      fogDensity: 0.0026,
      sun: '#eaf4ff',
      sunPosition: [-24, 70, -44],
      sunIntensity: 2.45,
      ambient: '#6f8ba6',
      ambientIntensity: 0.58,
      hemiSky: '#7ea6c9',
      hemiGround: '#3f4650',
      hemiIntensity: 0.7,
      horizon: '#a8d0e8',
      clarity: 0.92,
    },
    grade: { lift: 0.015, saturation: 1.04, gamma: 0.97, temperature: -0.22, grain: 0.1, vignette: 0.28, bloom: 1.3 },
    architecture: {
      styles: ['glass-tower', 'glass-steel', 'concrete', 'mid-century'],
      facadeColors: ['#2f3b4a', '#3d4c5e', '#4a5b6e', '#243040', '#55697d', '#1b2430'],
      minFloors: 10,
      maxFloors: 32,
      windowStyle: 'curtain-wall',
      setbacks: true,
      waterTowers: false,
      fireEscapes: false,
      roofAc: false,
      antennas: true,
      satelliteDishes: false,
      roofBillboards: false,
      glassRatio: 0.8,
    },
    vehicles: [
      { id: '2025-ev', kind: 'ev', label: 'Electric crossover', count: 5, length: 4.8, width: 1.95, height: 1.65, body: '#e6ecf2', accent: '#2f6fa8', movingRatio: 0.75, engineHz: 420 },
      { id: '2025-rideshare', kind: 'rideshare', label: 'Rideshare sedan', count: 4, length: 4.9, width: 1.92, height: 1.48, body: '#2f3a4a', accent: '#7fd0ff', movingRatio: 0.85, engineHz: 380 },
      { id: '2025-cargobike', kind: 'cargo-bike', label: 'Cargo e-bike', count: 3, length: 2.4, width: 0.75, height: 1.5, body: '#1f6f4a', accent: '#e8e4d0', movingRatio: 0.6, engineHz: 0 },
      { id: '2025-scooter', kind: 'scooter', label: 'Shared e-scooter', count: 4, length: 1.2, width: 0.5, height: 1.15, body: '#3fb0a0', accent: '#22262b', movingRatio: 0.6, engineHz: 0 },
      { id: '2025-bus', kind: 'bus', label: 'Electric articulated bus', count: 2, length: 12.5, width: 2.6, height: 3.2, body: '#dfe6ec', accent: '#2f8f7a', movingRatio: 0.9, engineHz: 300 },
      { id: '2025-taxi', kind: 'taxi', label: 'Robotaxi', count: 3, length: 4.7, width: 1.9, height: 1.6, body: '#1b2430', accent: '#6fe0c0', movingRatio: 0.9, engineHz: 400 },
    ],
    storefronts: [
      { id: '2025-coffee', name: 'Nimbus Coffee Lab', category: 'coffee', awning: '#32404f', display: 'COLD BREW 24/7 · REFILL STATION', signFormat: 'led', signColor: '#8fd8ff', glassTint: '#3f4c58' },
      { id: '2025-athletics', name: 'Vertex Athletics', category: 'athletics', awning: '#1f6f5a', display: 'RECYCLED KIT · RUN THE CITY', signFormat: 'media-facade', signColor: '#6fffc0', glassTint: '#37504a' },
      { id: '2025-tea', name: 'Cloud Nine Bubble Tea', category: 'tea', awning: '#5a4f8a', display: 'OAT MILK · TAPIOCA · NO STRAW', signFormat: 'led', signColor: '#ff9fd8', glassTint: '#4a4660' },
      { id: '2025-plants', name: 'Solstice Plant Shop', category: 'plants', awning: '#3f6f3f', display: 'PROPAGATION BAR · POTTED GREENS', signFormat: 'media-facade', signColor: '#c8ff8f', glassTint: '#42503f' },
      { id: '2025-vegan', name: 'Halo Vegan Kitchen', category: 'restaurant', awning: '#8a5f2f', display: 'PLANT-BASED · ZERO WASTE', signFormat: 'ticker', signColor: '#ffd08f', glassTint: '#5a5044' },
    ],
    advertisements: [
      { id: '2025-vertex', copy: 'VERTEX — RUN THE CITY', format: 'led', colors: ['#6fffc0', '#0f2a24'], placement: 'facade', emissive: true, scrolling: false },
      { id: '2025-nimbus', copy: 'NIMBUS — COLD BREW, 24/7', format: 'media-facade', colors: ['#8fd8ff', '#101c2a'], placement: 'facade', emissive: true, scrolling: true },
      { id: '2025-solaris', copy: 'SOLARIS EV — CHARGE AHEAD, PAY NOTHING', format: 'ticker', colors: ['#ffd08f', '#1b2430'], placement: 'rooftop', emissive: true, scrolling: true },
    ],
    outfits: [
      { id: '2025-techwear', label: 'Tech-wear commuter', colors: ['#1e242c', '#3fa8c9', '#0f1418'], skin: '#c99a72', accessory: 'hoodie', accessoryColor: '#2f3a44', hem: 0.56, silhouette: 'techwear' },
      { id: '2025-rider', label: 'Delivery rider', colors: ['#2f6a4a', '#e8e4d0', '#1a1e22'], skin: '#8a5f40', accessory: 'helmet', accessoryColor: '#e8e4d0', hem: 0.5, silhouette: 'techwear' },
      { id: '2025-commuter', label: 'Hybrid commuter', colors: ['#2a2f3a', '#5f6a78', '#d8dce0'], skin: '#e0b48c', accessory: 'phone', accessoryColor: '#5f6a78', hem: 0.54, silhouette: 'athletic' },
      { id: '2025-creative', label: 'Creative director', colors: ['#7a4fd0', '#f0e8d8', '#3a2f5a'], skin: '#b8805a', accessory: 'backpack', accessoryColor: '#3a2f5a', hem: 0.58, silhouette: 'techwear' },
      { id: '2025-runner', label: 'Morning runner', colors: ['#e06030', '#1f2226', '#f2eee6'], skin: '#dcae8a', accessory: 'none', accessoryColor: '#e06030', hem: 0.42, silhouette: 'athletic' },
      { id: '2025-student', label: 'Design student', colors: ['#3fbf9a', '#22262b', '#e0e4e8'], skin: '#e8c8a8', accessory: 'hoodie', accessoryColor: '#22262b', hem: 0.52, silhouette: 'techwear' },
    ],
    props: {
      lampStyle: 'led-organic',
      lampColor: '#eaf4ff',
      transit: 'electric-bus',
      telephonePoles: false,
      tramRails: false,
      bikeLane: true,
      newsstands: false,
      newspaperBoxes: false,
      busStopShelter: true,
      hydrantColor: '#5f6a78',
      benches: 8,
      planters: 8,
    },
    audio: ERA_AUDIO[2025],
    bannerText: 'VERTEX — RUN THE CITY',
    birds: 6,
    trafficSpeed: 1.25,
    crowdPace: 1.2,
  },
};

/** Era lookup by year. */
export function eraFor(year: Year): EraDefinition {
  return ERAS[year];
}

/** All five eras in timeline order. */
export function allEras(): EraDefinition[] {
  return YEARS.map((year) => ERAS[year]);
}

/** Era-friendly nickname, used in the transition caption. */
export function eraShortName(year: Year): string {
  return ERAS[year].title.split('·')[1]?.trim() ?? String(year);
}
