/**
 * Road traffic: the dispatched fleet that drives the city's road network.
 *
 * `VehiclesSystem` owns every vehicle the city runs and turns the commute
 * intent published by `src/sim/citizens.ts` into actual traffic on the road
 * graph generated by `src/sim/world.ts`:
 *
 * - **records** — each vehicle is a shared-contract `Vehicle` (kind, plate,
 *   capacity, owner, route, occupancy, fuel, speed, heading, position);
 * - **dispatch** — commute legs become rides (car, taxi, bus, tram, bicycle),
 *   the city's warehouses and shops become freight runs, and a scheduled
 *   service fleet holds the {@link MIN_ACTIVE_VEHICLES} floor around the clock:
 *   {@link DEFAULT_SERVICE_FLEET_SIZE} vehicles from
 *   {@link SERVICE_START_HOUR} to {@link SERVICE_END_HOUR}, and the leaner
 *   {@link DEFAULT_NIGHT_FLEET_SIZE} skeleton overnight, when every
 *   demand-dispatched vehicle has parked and been recycled;
 * - **driving** — vehicles follow real road-graph routes at kind-specific
 *   speeds, brake for the vehicle ahead and yield at intersections;
 * - **service** — commuters board at the entrance of the building they travel
 *   from and alight at the entrance of the building they travel to, with
 *   `Vehicle.occupancy`, `Vehicle.occupantIds` and `Citizen.vehicleId` kept in
 *   sync while they ride;
 * - **recycling** — a finished vehicle parks, refuels and drops into a pool,
 *   where the *same object* (same id, same plate) is dispatched again. Nothing
 *   is discarded, so a multi-day soak keeps a bounded fleet instead of leaking
 *   one vehicle per trip.
 *
 * The module is DOM-free: it imports `./clock`, `./engine`, `./rng`, `./types`,
 * `./world` and the citizen *types* only, and never touches browser globals.
 * The economy is out of scope here - freight demand is derived from the world's
 * own warehouse/factory/shop geometry and used as a dispatch signal.
 */

import { MINUTES_PER_HOUR } from './clock';
import type { CitizensSystem, CommuteIntent, CommuteMode } from './citizens';
import type { EngineContext, SimSystem, SimulationEngine } from './engine';
import { createRng } from './rng';
import type { Rng } from './rng';
import { VEHICLE_KINDS } from './types';
import type {
  Building,
  Citizen,
  CompanySector,
  EntityId,
  RoadNode,
  RoadSegment,
  Vehicle,
  VehicleKind,
  VehicleRoute,
  Vec2,
  WorldMap,
} from './types';
import { buildingCenter, distanceBetweenPoints } from './world';
import type { RoutePath } from './world';

/* ------------------------------------------------------------- constants -- */

/** Engine system name used by the application composition. */
export const VEHICLES_SYSTEM_NAME = 'vehicles';

/**
 * Vehicles the city promises to keep on the road at every hour of the day, and
 * in particular through the commuter peaks in {@link COMMUTE_PEAKS}.
 */
export const MIN_ACTIVE_VEHICLES = 10;

/** Vehicles the scheduled service runs during service hours (peaks included). */
export const DEFAULT_SERVICE_FLEET_SIZE = 12;

/**
 * Vehicles kept running overnight. The city promises at least
 * {@link MIN_ACTIVE_VEHICLES} vehicles at every hour of the day, so the
 * overnight skeleton is exactly that floor: the demand-dispatched cars, buses,
 * trams and bicycles park and recycle, and only the scheduled service runs.
 */
export const DEFAULT_NIGHT_FLEET_SIZE = MIN_ACTIVE_VEHICLES;

/** Hard cap on simultaneously active vehicles, so demand cannot run away. */
export const DEFAULT_MAX_ACTIVE_VEHICLES = 48;

/** Hour-of-day the scheduled service fleet starts running. */
export const SERVICE_START_HOUR = 5;

/** Hour-of-day the scheduled service fleet stops running. */
export const SERVICE_END_HOUR = 23;

/**
 * The world's `speedLimit` values are walking-scale planning figures (0.45-0.6
 * tiles per sim-minute, roughly 14-19 px/min). Road traffic drives at a paced
 * multiple of them, which is what makes a crosstown trip take a plausible slice
 * of the day instead of most of it. Kind ceilings in {@link VEHICLE_KIND_SPECS}
 * still apply on top.
 */
export const ROAD_PACE_MULTIPLIER = 6;

/** A commuter peak: the stretch of day the >=10 vehicle floor has to hold in. */
export interface CommutePeak {
  readonly id: string;
  readonly label: string;
  readonly startHour: number;
  readonly endHour: number;
}

/** Morning and evening commuter peaks, driven by the citizens' shift patterns. */
export const COMMUTE_PEAKS: readonly CommutePeak[] = [
  { id: 'morning', label: 'morning peak', startHour: 5, endHour: 10 },
  { id: 'evening', label: 'evening peak', startHour: 16, endHour: 21 },
];

/** Tiles a vehicle looks ahead for a claim held by another vehicle. */
const NODE_YIELD_DISTANCE_TILES = 2.5;
/** Distance from a node at which a vehicle claims it for this tick. */
const NODE_ZONE_TILES = 2;
/** After this long waiting at an occupied node a vehicle creeps forward. */
const MAX_YIELD_MINUTES = 3;
/** Creep speed as a fraction of free flow, once a vehicle has waited too long. */
const YIELD_CREEP_FACTOR = 0.35;
/** Time a follower wants between itself and the vehicle ahead. */
const FOLLOW_HEADWAY_MINUTES = 1.1;
/** Extra gap a follower keeps on top of the leader's own length. */
const FOLLOW_GAP_TILES = 1.5;
/** Safety valve: how many road segments one tick may cross. */
const MAX_SEGMENTS_PER_TICK = 8;
/** How long a commuter waits for their ride before giving up. */
const MAX_RIDER_WAIT_MINUTES = 60;
/** How long a scheduled transit vehicle stays out on its line. */
const TRANSIT_SERVICE_MINUTES = 150;
/** How long a delivery van stays out on its run. */
const FREIGHT_SERVICE_MINUTES = 120;
/** Shortest freight corridor worth dispatching a van for, in tiles. */
const MIN_FREIGHT_DISTANCE_TILES = 25;
/** Stop dwell a pre-positioned ride waits for a commuter at the kerb. */
const PREPOSITIONED_WAIT_MINUTES = 6;
/** Ring buffer size of the recent event log. */
const EVENT_LOG_LIMIT = 1024;
/** Corridors a coverage slot may pick from, spread over the busiest ones. */
const CORRIDOR_CHOICE_SPREAD = 5;

/* -------------------------------------------------------------- kind data -- */

/** What a vehicle is out on the road for. */
export type VehicleRole = 'commute' | 'transit' | 'freight';

/** What a vehicle is doing right now. */
export type VehicleActivity = 'driving' | 'dwelling' | 'parked';

/** Everything data-driven about a vehicle kind. */
export interface VehicleKindSpec {
  readonly kind: VehicleKind;
  /** Label used by the inspector and the minimap legend. */
  readonly label: string;
  readonly role: VehicleRole;
  /** Maximum simultaneous riders/cargo units. */
  readonly capacity: number;
  /** Free-flow ceiling in tiles per sim-minute. */
  readonly maxSpeed: number;
  /** Length of asphalt the vehicle occupies, in tiles. */
  readonly lengthTiles: number;
  readonly fuelCapacity: number;
  /** Fuel units burned per tile driven. */
  readonly fuelPerTile: number;
  /** Minutes spent at each stop. */
  readonly dwellMinutes: number;
  readonly color: string;
  /** Prefix of the generated license plates. */
  readonly platePrefix: string;
}

/**
 * The fleet's kind table. Speeds are tiles per sim-minute; a full tank always
 * outlasts a service run, so fuel is a live reading rather than a failure mode.
 */
export const VEHICLE_KIND_SPECS: Readonly<Record<VehicleKind, VehicleKindSpec>> = {
  car: {
    kind: 'car',
    label: 'car',
    role: 'commute',
    capacity: 4,
    maxSpeed: 2.9,
    lengthTiles: 1.2,
    fuelCapacity: 45,
    fuelPerTile: 0.05,
    dwellMinutes: 1,
    color: '#e0e6f2',
    platePrefix: 'CT',
  },
  taxi: {
    kind: 'taxi',
    label: 'taxi',
    role: 'commute',
    capacity: 4,
    maxSpeed: 3.1,
    lengthTiles: 1.2,
    fuelCapacity: 45,
    fuelPerTile: 0.055,
    dwellMinutes: 1,
    color: '#f2c94c',
    platePrefix: 'TX',
  },
  bus: {
    kind: 'bus',
    label: 'bus',
    role: 'transit',
    capacity: 36,
    maxSpeed: 1.9,
    lengthTiles: 3.2,
    fuelCapacity: 180,
    fuelPerTile: 0.16,
    dwellMinutes: 1,
    color: '#4f8bd6',
    platePrefix: 'BU',
  },
  tram: {
    kind: 'tram',
    label: 'tram',
    role: 'transit',
    capacity: 60,
    maxSpeed: 2.4,
    lengthTiles: 4.5,
    fuelCapacity: 240,
    fuelPerTile: 0.12,
    dwellMinutes: 1,
    color: '#69b58f',
    platePrefix: 'TR',
  },
  truck: {
    kind: 'truck',
    label: 'delivery van',
    role: 'freight',
    capacity: 12,
    maxSpeed: 2.2,
    lengthTiles: 2.4,
    fuelCapacity: 90,
    fuelPerTile: 0.11,
    dwellMinutes: 2,
    color: '#c9884a',
    platePrefix: 'DV',
  },
  bicycle: {
    kind: 'bicycle',
    label: 'bicycle',
    role: 'commute',
    capacity: 1,
    maxSpeed: 0.9,
    lengthTiles: 0.6,
    fuelCapacity: 1.2,
    fuelPerTile: 0.001,
    dwellMinutes: 1,
    color: '#8fb7d8',
    platePrefix: 'BC',
  },
};

/** Vehicle kind that carries a commuter travelling in the given mode. */
export function vehicleKindForCommuteMode(mode: CommuteMode): VehicleKind | null {
  switch (mode) {
    case 'car':
      return 'car';
    case 'bus':
      return 'bus';
    case 'tram':
      return 'tram';
    case 'bicycle':
      return 'bicycle';
    default:
      return null;
  }
}

/** Whether a minute-of-day falls inside one of the commuter peaks. */
export function isCommutePeak(minuteOfDay: number): boolean {
  return peakForMinute(minuteOfDay) !== null;
}

/** The peak a minute-of-day belongs to, or `null` outside every peak. */
export function peakForMinute(minuteOfDay: number): CommutePeak | null {
  const hour = Math.floor(((minuteOfDay % 1440) + 1440) % 1440 / MINUTES_PER_HOUR);
  for (const peak of COMMUTE_PEAKS) {
    if (hour >= peak.startHour && hour < peak.endHour) {
      return peak;
    }
  }
  return null;
}

/** Speed a kind may use on a segment with the given speed limit. */
export function pacedSpeedLimit(segmentSpeedLimit: number, kind: VehicleKind): number {
  const spec = VEHICLE_KIND_SPECS[kind];
  return Math.min(spec.maxSpeed, segmentSpeedLimit * ROAD_PACE_MULTIPLIER);
}

/* ---------------------------------------------------------------- inputs -- */

/**
 * The slice of the world the traffic system needs: the shared `WorldMap`
 * contract plus the routing lookups `CityWorld` already provides.
 */
export interface VehicleWorld extends WorldMap {
  readonly buildings: Building[];
  roadNodeById(nodeId: EntityId): RoadNode | null;
  routeBetweenNodes(fromNodeId: EntityId, toNodeId: EntityId): RoutePath | null;
  nearestRoadNode(point: Vec2): RoadNode;
}

/** A commute corridor the fleet may work: one building to another. */
export interface CommuteCorridor {
  readonly id: string;
  readonly kind: VehicleKind;
  readonly mode: CommuteMode;
  readonly fromBuildingId: EntityId;
  readonly toBuildingId: EntityId;
  readonly fromNodeId: EntityId;
  readonly toNodeId: EntityId;
  readonly distanceTiles: number;
  /** Commute legs in the roster that use this corridor. */
  readonly legs: number;
}

/** A freight corridor: goods from a warehouse/factory to a shop or store. */
export interface FreightRun {
  readonly id: string;
  readonly vehicleKind: VehicleKind;
  readonly sourceBuildingId: EntityId;
  readonly destinationBuildingId: EntityId;
  readonly sourceNodeId: EntityId;
  readonly destinationNodeId: EntityId;
  readonly distanceTiles: number;
}

/** One stop of a vehicle's plan. */
export interface VehicleStop {
  readonly nodeId: EntityId;
  readonly buildingId: EntityId | null;
  readonly action: 'board' | 'alight' | 'service' | 'park';
  readonly dwellMinutes: number;
}

/* --------------------------------------------------------------- options -- */

/** Constructor options for {@link VehiclesSystem}. */
export interface VehiclesOptions {
  /** The generated city the fleet drives in. */
  readonly world: VehicleWorld;
  /** Citizen roster that supplies commute intent; optional for fleet-only use. */
  readonly citizens?: CitizensSystem | null;
  /** Fleet seed; defaults to the world seed (or the world id). */
  readonly seed?: number | string;
  /** Engine system name; defaults to {@link VEHICLES_SYSTEM_NAME}. */
  readonly systemName?: string;
  /** Vehicles kept on the road during service hours. Defaults to 12. */
  readonly serviceFleetSize?: number;
  /** Vehicles kept on the road at night. Defaults to 4. */
  readonly nightFleetSize?: number;
  /** Hard cap on simultaneously active vehicles. Defaults to 48. */
  readonly maxActiveVehicles?: number;
}

/* ----------------------------------------------------------------- events -- */

/** Kinds of fleet event the system publishes for tests, HUD and inspectors. */
export type VehicleEventKind = 'dispatch' | 'reuse' | 'board' | 'alight' | 'park';

/** One fleet event, timestamped with sim time. */
export interface VehicleEvent {
  readonly kind: VehicleEventKind;
  readonly vehicleId: EntityId;
  readonly vehicleKind: VehicleKind;
  readonly role: VehicleRole;
  readonly citizenId: EntityId | null;
  readonly buildingId: EntityId | null;
  readonly nodeId: EntityId | null;
  readonly day: number;
  readonly minuteOfDay: number;
  readonly occupancy: number;
}

/* ------------------------------------------------------------ inspector -- */

/** One passenger aboard a vehicle, for the detail inspector. */
export interface VehiclePassenger {
  readonly citizenId: EntityId;
  readonly originBuildingId: EntityId;
  readonly destinationBuildingId: EntityId;
  readonly destinationNodeId: EntityId;
  readonly boardedAtMinute: number;
}

/** Everything the entity inspector shows for one vehicle. */
export interface VehicleDetails {
  readonly id: EntityId;
  readonly kind: VehicleKind;
  readonly kindLabel: string;
  readonly plate: string;
  readonly capacity: number;
  readonly occupancy: number;
  readonly occupantIds: readonly EntityId[];
  readonly fuel: number;
  readonly fuelCapacity: number;
  readonly speed: number;
  readonly headingRadians: number;
  readonly position: Vec2;
  readonly currentNodeId: EntityId | null;
  readonly targetNodeId: EntityId | null;
  readonly ownerCompanyId: EntityId | null;
  readonly color: string;
  readonly role: VehicleRole;
  readonly activity: VehicleActivity;
  readonly route: VehicleRoute;
  readonly stops: readonly VehicleStop[];
  readonly nextStopNodeId: EntityId | null;
  readonly nextStopBuildingId: EntityId | null;
  readonly nextStopBuildingName: string | null;
  readonly passengers: readonly VehiclePassenger[];
  readonly corridorKey: string | null;
  readonly distanceTiles: number;
  readonly completedTrips: number;
}

/** Aggregate figures over the fleet, for tests, HUD and diagnostics. */
export interface VehiclesStats {
  activeVehicles: number;
  /** Highest simultaneous count seen since construction. */
  peakActiveVehicles: number;
  parkedVehicles: number;
  /** Vehicle objects ever allocated (bounded by the peak concurrency). */
  createdVehicles: number;
  /** Dispatches that reused a parked object instead of allocating one. */
  reusedVehicles: number;
  dispatches: number;
  parks: number;
  refuels: number;
  boardings: number;
  alightings: number;
  yieldTicks: number;
  /** How often a vehicle began waiting for an occupied intersection. */
  yieldStarts: number;
  followTicks: number;
  /** Commute intents the fleet could not serve (cap reached or unroutable). */
  unservedIntents: number;
  expiredWaits: number;
  /** Mean riders per active vehicle. */
  averageOccupancy: number;
  fuelRemaining: number;
  totalDistanceTiles: number;
  freightDeliveries: number;
  kindCounts: Record<VehicleKind, number>;
  roleCounts: Record<VehicleRole, number>;
  /** Peak the latest update fell in, or `null` outside every peak. */
  peakLabel: string | null;
  /** Riders waiting at a stop or riding right now. */
  ridersInTransit: number;
}

/* ------------------------------------------------------------ internals -- */

/** A commuter the fleet is carrying or about to carry. */
interface FleetRider {
  readonly citizenId: EntityId;
  readonly mode: CommuteMode;
  readonly corridorKey: string;
  readonly originBuildingId: EntityId;
  readonly destinationBuildingId: EntityId;
  readonly originNodeId: EntityId;
  readonly destinationNodeId: EntityId;
  readonly allowedKinds: readonly VehicleKind[];
  readonly departMinute: number;
  readonly expiresAtMinute: number;
  vehicleId: EntityId | null;
  boardedAtMinute: number;
}

/** The current leg of a route: which segment is being driven, and how far. */
interface VehicleLeg {
  nodeIds: EntityId[];
  index: number;
  fromNodeId: EntityId;
  toNodeId: EntityId;
  segmentId: EntityId | null;
  length: number;
  travelled: number;
}

/** Everything the system tracks about one active vehicle. */
interface VehicleRuntime {
  readonly vehicle: Vehicle;
  readonly spec: VehicleKindSpec;
  readonly role: VehicleRole;
  readonly corridorKey: string | null;
  readonly coverageSlot: number | null;
  readonly createdAtMinute: number;
  readonly serviceUntilMinute: number;
  stops: VehicleStop[];
  stopIndex: number;
  leg: VehicleLeg;
  activity: VehicleActivity;
  dwellRemaining: number;
  riders: FleetRider[];
  retiring: boolean;
  yieldSinceMinute: number | null;
  distanceTiles: number;
  completedTrips: number;
}

/** Shape of the internal dispatch helper used by every dispatch path. */
interface SpawnRequest {
  kind: VehicleKind;
  role: VehicleRole;
  stops: VehicleStop[];
  loop: boolean;
  routeKind: VehicleRoute['kind'];
  spawnAtNodeId: EntityId;
  corridorKey: string | null;
  coverageSlot: number | null;
  serviceUntilMinute: number;
  ownerCompanyId: EntityId | null;
}

/* ------------------------------------------------------------ fleet plan -- */

/** Role/kind of each scheduled service slot, in dispatch order. */
const COVERAGE_PLAN: readonly { readonly role: VehicleRole; readonly kind: VehicleKind }[] = [
  { role: 'transit', kind: 'bus' },
  { role: 'freight', kind: 'truck' },
  { role: 'commute', kind: 'car' },
  { role: 'transit', kind: 'tram' },
  { role: 'transit', kind: 'bus' },
  { role: 'freight', kind: 'truck' },
  { role: 'commute', kind: 'car' },
  { role: 'transit', kind: 'tram' },
  { role: 'commute', kind: 'car' },
  { role: 'freight', kind: 'truck' },
  { role: 'transit', kind: 'bus' },
  { role: 'commute', kind: 'car' },
];

/** Building kinds that ship goods out of the city's industrial quarter. */
const FREIGHT_SOURCE_KINDS: readonly Building['kind'][] = ['warehouse', 'factory'];
/** Building kinds that receive those goods. */
const FREIGHT_DESTINATION_KINDS: readonly Building['kind'][] = ['shop', 'warehouse'];
/** Building kinds that offer work, used by the citizen-free corridor fallback. */
const WORKPLACE_KINDS: readonly Building['kind'][] = [
  'office',
  'shop',
  'factory',
  'warehouse',
  'school',
  'hospital',
  'civic',
];

function compareIds(left: string, right: string): number {
  if (left < right) {
    return -1;
  }
  return left > right ? 1 : 0;
}

/** Tolerance for "the two vehicles are at the same point of a leg". */
const LEG_EPSILON_TILES = 1e-9;

/**
 * Strict order along a leg: a vehicle is *ahead* when it has driven further, or
 * when both sit at the same distance and the lower id wins the tie. The id
 * tie-break matters: without it two side-by-side vehicles would each treat the
 * other as "the vehicle in front" and freeze the whole block.
 */
function isAheadOnLeg(ahead: VehicleRuntime, behind: VehicleRuntime): boolean {
  const delta = ahead.leg.travelled - behind.leg.travelled;
  if (delta > LEG_EPSILON_TILES) {
    return true;
  }
  if (delta < -LEG_EPSILON_TILES) {
    return false;
  }
  return compareIds(ahead.vehicle.id, behind.vehicle.id) < 0;
}

function clamp(value: number, min: number, max: number): number {
  if (value < min) {
    return min;
  }
  return value > max ? max : value;
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

/**
 * The dispatched vehicle fleet.
 *
 * Build it with the generated world (and, in the app, the citizen system):
 *
 * ```ts
 * const vehicles = new VehiclesSystem({ world, citizens });
 * engine.attach(citizens);
 * engine.attach(vehicles);
 * ```
 *
 * Attach the traffic system *after* the citizen system: the citizen system
 * clears `Citizen.vehicleId` on every step, and the traffic system rewrites it
 * for the riders it carries.
 */
export class VehiclesSystem implements SimSystem {
  readonly name: string;
  readonly world: VehicleWorld;
  readonly seed: number | string;
  /** Citizen roster that supplies commute intent, when one was supplied. */
  readonly citizens: CitizensSystem | null;
  readonly serviceFleetSize: number;
  readonly nightFleetSize: number;
  readonly maxActiveVehicles: number;
  /** Road node new vehicles enter the network from (the city centre). */
  readonly depotNodeId: EntityId;

  private readonly activeRuntimes: VehicleRuntime[] = [];
  private readonly runtimeById = new Map<EntityId, VehicleRuntime>();
  private readonly poolByKind = new Map<VehicleKind, Vehicle[]>();
  private readonly waitingByNode = new Map<EntityId, FleetRider[]>();
  private readonly servedIntentKeys = new Set<string>();
  private readonly nodeById = new Map<EntityId, RoadNode>();
  private readonly segmentById = new Map<EntityId, RoadSegment>();
  private readonly buildingById = new Map<EntityId, Building>();
  private readonly citizenIndex = new Map<EntityId, Citizen>();
  private readonly companyBySector = new Map<CompanySector, EntityId>();
  private readonly corridorsByKind: Record<'car' | 'bus' | 'tram' | 'bicycle', CommuteCorridor[]> = {
    car: [],
    bus: [],
    tram: [],
    bicycle: [],
  };
  private readonly corridorCursor: Record<'car' | 'bus' | 'tram' | 'bicycle', number> = {
    car: 0,
    bus: 0,
    tram: 0,
    bicycle: 0,
  };
  private readonly freightRunList: FreightRun[] = [];
  private readonly coverageAssignments = new Map<number, EntityId>();
  private readonly eventLog: VehicleEvent[] = [];
  private readonly rng: Rng;

  private engineRef: SimulationEngine | null = null;
  private updateCountValue = 0;
  private minuteOfDayValue = 0;
  private absoluteMinuteValue = 0;
  private dayValue = 0;
  private lastDay = -1;
  private createdVehicleCountValue = 0;
  private reuseCountValue = 0;
  private dispatchCountValue = 0;
  private parkCountValue = 0;
  private refuelCountValue = 0;
  private boardCountValue = 0;
  private alightCountValue = 0;
  private yieldTickValue = 0;
  private yieldStartValue = 0;
  private followTickValue = 0;
  private unservedIntentValue = 0;
  private expiredWaitValue = 0;
  private peakActiveValue = 0;
  private distanceValue = 0;
  private deliveryValue = 0;

  constructor(options: VehiclesOptions) {
    if (!options || !options.world) {
      throw new TypeError('new VehiclesSystem(options) expects options.world');
    }
    const world = options.world;
    if (!Array.isArray(world.nodes) || world.nodes.length === 0) {
      throw new Error('VehiclesSystem needs a city with a road network');
    }
    if (!Array.isArray(world.buildings) || world.buildings.length === 0) {
      throw new Error('VehiclesSystem needs a city with buildings to serve');
    }
    this.world = world;
    this.name = options.systemName ?? VEHICLES_SYSTEM_NAME;
    this.citizens = options.citizens ?? null;

    this.serviceFleetSize = options.serviceFleetSize ?? DEFAULT_SERVICE_FLEET_SIZE;
    if (!Number.isInteger(this.serviceFleetSize) || this.serviceFleetSize < MIN_ACTIVE_VEHICLES) {
      throw new RangeError(
        `VehiclesSystem serviceFleetSize must be an integer >= ${MIN_ACTIVE_VEHICLES}, received ${this.serviceFleetSize}`,
      );
    }
    this.nightFleetSize = options.nightFleetSize ?? DEFAULT_NIGHT_FLEET_SIZE;
    if (!Number.isInteger(this.nightFleetSize) || this.nightFleetSize < 1) {
      throw new RangeError(
        `VehiclesSystem nightFleetSize must be a positive integer, received ${this.nightFleetSize}`,
      );
    }
    this.maxActiveVehicles = options.maxActiveVehicles ?? DEFAULT_MAX_ACTIVE_VEHICLES;
    if (!Number.isInteger(this.maxActiveVehicles) || this.maxActiveVehicles < this.serviceFleetSize) {
      throw new RangeError(
        `VehiclesSystem maxActiveVehicles must be an integer >= serviceFleetSize (${this.serviceFleetSize}), received ${this.maxActiveVehicles}`,
      );
    }

    const worldSeed = (world as { seed?: unknown }).seed;
    this.seed = options.seed ?? (typeof worldSeed === 'number' ? worldSeed : world.id);
    this.rng = createRng(this.seed).fork('vehicle-fleet');

    for (const node of world.nodes) {
      this.nodeById.set(node.id, node);
    }
    for (const segment of world.segments) {
      this.segmentById.set(segment.id, segment);
    }
    for (const building of world.buildings) {
      this.buildingById.set(building.id, building);
    }
    for (const citizen of world.citizens) {
      this.citizenIndex.set(citizen.id, citizen);
    }
    for (const kind of VEHICLE_KINDS) {
      this.poolByKind.set(kind, []);
    }
    for (const company of [...world.companies].sort((left, right) => compareIds(left.id, right.id))) {
      if (!this.companyBySector.has(company.sector)) {
        this.companyBySector.set(company.sector, company.id);
      }
    }

    const fallbackDepot = [...world.nodes].sort((left, right) => compareIds(left.id, right.id))[0];
    this.depotNodeId =
      world.spawnNodeId !== null && this.nodeById.has(world.spawnNodeId)
        ? world.spawnNodeId
        : fallbackDepot.id;

    this.buildCorridors();
    this.freightRunList = this.buildFreightRuns();
  }

  /* ------------------------------------------------------------ lifecycle -- */

  /** Registers this system on an engine; returns the engine's detach function. */
  attach(engine: SimulationEngine): () => boolean {
    return engine.attach(this);
  }

  /** Called once when the engine attaches the system. */
  onAttach(context: EngineContext): void {
    if (this.engineRef !== null && this.engineRef !== context.engine) {
      throw new Error('VehiclesSystem is already attached to another SimulationEngine');
    }
    this.engineRef = context.engine;
    this.updateCountValue = 0;
    this.lastDay = -1;
    this.servedIntentKeys.clear();
    this.minuteOfDayValue = context.clock.hourOfDay * MINUTES_PER_HOUR + context.clock.minuteOfHour;
    this.absoluteMinuteValue = context.clock.totalMinutes;
    this.dayValue = context.clock.day;
  }

  /** Called once when the system is detached or the engine is disposed. */
  onDetach(): void {
    for (const runtime of [...this.activeRuntimes]) {
      this.parkVehicle(runtime);
    }
    this.waitingByNode.clear();
    this.coverageAssignments.clear();
    this.engineRef = null;
  }

  /**
   * One fixed engine step: absorb new commute intent, top the fleet up to the
   * service floor, drive every vehicle, then refresh the riding links.
   */
  update(context: EngineContext): void {
    this.updateCountValue += 1;
    this.absoluteMinuteValue = context.clock.totalMinutes;
    this.minuteOfDayValue = context.clock.hourOfDay * MINUTES_PER_HOUR + context.clock.minuteOfHour;
    this.dayValue = context.clock.day;
    if (this.dayValue !== this.lastDay) {
      this.lastDay = this.dayValue;
      this.servedIntentKeys.clear();
    }
    this.expireWaitingRiders();
    this.servePendingIntents();
    this.ensureCoverage();
    this.advanceFleet(context.deltaMinutes);
    // Vehicles that parked during the step are replaced in the same tick, so the
    // fleet never dips below the floor the current hour calls for.
    this.ensureCoverage();
    this.syncRiderLinks();
    if (this.activeRuntimes.length > this.peakActiveValue) {
      this.peakActiveValue = this.activeRuntimes.length;
    }
  }

  /* -------------------------------------------------------------- reading -- */

  get attached(): boolean {
    return this.engineRef !== null;
  }

  /** Fixed steps applied through the engine so far. */
  get updateCount(): number {
    return this.updateCountValue;
  }

  /** Minute-of-day of the latest reading. */
  get minuteOfDay(): number {
    return this.minuteOfDayValue;
  }

  /** Vehicles currently driving or dwelling on the network. */
  get activeCount(): number {
    return this.activeRuntimes.length;
  }

  /** Recycled vehicle objects waiting in the parking pool. */
  get parkedCount(): number {
    let total = 0;
    for (const pool of this.poolByKind.values()) {
      total += pool.length;
    }
    return total;
  }

  /** Highest simultaneous vehicle count seen since construction. */
  get peakActiveCount(): number {
    return this.peakActiveValue;
  }

  /** The active vehicles, in dispatch order. */
  activeVehicles(): readonly Vehicle[] {
    return this.activeRuntimes.map((runtime) => runtime.vehicle);
  }

  /** The recycled vehicle objects waiting in the parking pool. */
  parkedVehicles(): readonly Vehicle[] {
    const parked: Vehicle[] = [];
    for (const kind of VEHICLE_KINDS) {
      parked.push(...(this.poolByKind.get(kind) ?? []));
    }
    return parked;
  }

  /** Recent fleet events, oldest first (bounded ring buffer). */
  get events(): readonly VehicleEvent[] {
    return this.eventLog;
  }

  /** Events of one kind, oldest first. */
  eventsOfKind(kind: VehicleEventKind): VehicleEvent[] {
    return this.eventLog.filter((event) => event.kind === kind);
  }

  /** Riders waiting at a stop or riding right now. */
  get ridersInTransit(): number {
    let waiting = 0;
    for (const riders of this.waitingByNode.values()) {
      waiting += riders.length;
    }
    for (const runtime of this.activeRuntimes) {
      waiting += runtime.riders.length;
    }
    return waiting;
  }

  /** Commute corridors the roster actually uses, busiest first. */
  commuteCorridors(): readonly CommuteCorridor[] {
    return [...this.corridorsByKind.car, ...this.corridorsByKind.bus, ...this.corridorsByKind.tram, ...this.corridorsByKind.bicycle];
  }

  /** Commuter corridors worked by buses and trams. */
  transitCorridors(): readonly CommuteCorridor[] {
    return [...this.corridorsByKind.bus, ...this.corridorsByKind.tram];
  }

  /** Freight corridors derived from the city's industrial and retail layout. */
  freightRuns(): readonly FreightRun[] {
    return this.freightRunList;
  }

  vehicleById(vehicleId: EntityId): Vehicle | null {
    const active = this.runtimeById.get(vehicleId);
    if (active) {
      return active.vehicle;
    }
    for (const kind of VEHICLE_KINDS) {
      const pooled = (this.poolByKind.get(kind) ?? []).find((vehicle) => vehicle.id === vehicleId);
      if (pooled) {
        return pooled;
      }
    }
    return null;
  }

  /** Whether a vehicle object belongs to this fleet. */
  owns(vehicle: Vehicle): boolean {
    return this.runtimeById.has(vehicle.id) || this.vehicleById(vehicle.id) === vehicle;
  }

  /** Everything the detail inspector shows for one vehicle, parked or active. */
  detailsFor(vehicleId: EntityId): VehicleDetails | null {
    const runtime = this.runtimeById.get(vehicleId);
    if (runtime) {
      const vehicle = runtime.vehicle;
      const nextStop = runtime.stops[runtime.stopIndex] ?? null;
      return {
        id: vehicle.id,
        kind: vehicle.kind,
        kindLabel: runtime.spec.label,
        plate: vehicle.plate,
        capacity: vehicle.capacity,
        occupancy: vehicle.occupancy,
        occupantIds: [...vehicle.occupantIds],
        fuel: vehicle.fuel,
        fuelCapacity: vehicle.fuelCapacity,
        speed: vehicle.speed,
        headingRadians: vehicle.headingRadians,
        position: { ...vehicle.position },
        currentNodeId: vehicle.currentNodeId,
        targetNodeId: vehicle.targetNodeId,
        ownerCompanyId: vehicle.ownerCompanyId,
        color: vehicle.color,
        role: runtime.role,
        activity: runtime.activity,
        route: { ...vehicle.route, stopNodeIds: [...vehicle.route.stopNodeIds] },
        stops: runtime.stops.map((stop) => ({ ...stop })),
        nextStopNodeId: nextStop?.nodeId ?? null,
        nextStopBuildingId: nextStop?.buildingId ?? null,
        nextStopBuildingName: nextStop?.buildingId
          ? this.buildingById.get(nextStop.buildingId)?.name ?? null
          : null,
        passengers: runtime.riders.map((rider) => ({
          citizenId: rider.citizenId,
          originBuildingId: rider.originBuildingId,
          destinationBuildingId: rider.destinationBuildingId,
          destinationNodeId: rider.destinationNodeId,
          boardedAtMinute: rider.boardedAtMinute,
        })),
        corridorKey: runtime.corridorKey,
        distanceTiles: round2(runtime.distanceTiles),
        completedTrips: runtime.completedTrips,
      };
    }
    const parked = this.vehicleById(vehicleId);
    if (!parked) {
      return null;
    }
    const spec = VEHICLE_KIND_SPECS[parked.kind];
    return {
      id: parked.id,
      kind: parked.kind,
      kindLabel: spec.label,
      plate: parked.plate,
      capacity: parked.capacity,
      occupancy: parked.occupancy,
      occupantIds: [...parked.occupantIds],
      fuel: parked.fuel,
      fuelCapacity: parked.fuelCapacity,
      speed: 0,
      headingRadians: parked.headingRadians,
      position: { ...parked.position },
      currentNodeId: parked.currentNodeId,
      targetNodeId: null,
      ownerCompanyId: parked.ownerCompanyId,
      color: parked.color,
      role: spec.role,
      activity: 'parked',
      route: { ...parked.route, stopNodeIds: [...parked.route.stopNodeIds] },
      stops: [],
      nextStopNodeId: null,
      nextStopBuildingId: null,
      nextStopBuildingName: null,
      passengers: [],
      corridorKey: null,
      distanceTiles: 0,
      completedTrips: 0,
    };
  }

  /** Aggregate figures over the fleet and its service history. */
  stats(): VehiclesStats {
    const kindCounts = {} as Record<VehicleKind, number>;
    for (const kind of VEHICLE_KINDS) {
      kindCounts[kind] = 0;
    }
    const roleCounts: Record<VehicleRole, number> = { commute: 0, transit: 0, freight: 0 };
    let occupancy = 0;
    let fuel = 0;
    for (const runtime of this.activeRuntimes) {
      kindCounts[runtime.vehicle.kind] += 1;
      roleCounts[runtime.role] += 1;
      occupancy += runtime.vehicle.occupancy;
      fuel += runtime.vehicle.fuel;
    }
    const active = this.activeRuntimes.length;
    return {
      activeVehicles: active,
      peakActiveVehicles: this.peakActiveValue,
      parkedVehicles: this.parkedCount,
      createdVehicles: this.createdVehicleCountValue,
      reusedVehicles: this.reuseCountValue,
      dispatches: this.dispatchCountValue,
      parks: this.parkCountValue,
      refuels: this.refuelCountValue,
      boardings: this.boardCountValue,
      alightings: this.alightCountValue,
      yieldTicks: this.yieldTickValue,
      yieldStarts: this.yieldStartValue,
      followTicks: this.followTickValue,
      unservedIntents: this.unservedIntentValue,
      expiredWaits: this.expiredWaitValue,
      averageOccupancy: active === 0 ? 0 : round2(occupancy / active),
      fuelRemaining: round2(fuel),
      totalDistanceTiles: round2(this.distanceValue),
      freightDeliveries: this.deliveryValue,
      kindCounts,
      roleCounts,
      peakLabel: peakForMinute(this.minuteOfDayValue)?.label ?? null,
      ridersInTransit: this.ridersInTransit,
    };
  }

  /** Number of active vehicles of each kind. */
  kindCounts(): Record<VehicleKind, number> {
    return this.stats().kindCounts;
  }

  /* ------------------------------------------------------------- dispatch -- */

  /**
   * Dispatches a ride for one commuter commute leg. The vehicle appears at the
   * building the commuter travels from, picks them up there and drops them at
   * the building they travel to. Riders already waiting on the same corridor
   * share the vehicle while it still has capacity.
   */
  dispatchRide(intent: CommuteIntent): Vehicle | null {
    const kind = vehicleKindForCommuteMode(intent.mode);
    if (kind === null) {
      return null;
    }
    const originNodeId = this.nodeForBuilding(intent.fromBuildingId);
    const destinationNodeId = this.nodeForBuilding(intent.toBuildingId);
    if (!originNodeId || !destinationNodeId) {
      this.unservedIntentValue += 1;
      return null;
    }
    if (originNodeId === destinationNodeId) {
      // Both buildings open onto the same road node: that is a walk, not a ride.
      return null;
    }
    const rider = this.riderForIntent(intent, kind, originNodeId, destinationNodeId);
    const existing = this.findServableVehicle(kind, rider);
    this.registerWaitingRider(rider);
    if (existing) {
      return existing.vehicle;
    }
    return this.dispatchRideVehicle(kind, rider);
  }

  /**
   * Low-level dispatch used by tests and by the scheduled service: sends a
   * vehicle of `kind` from `spawnAtNodeId` (the depot by default) to
   * `fromNodeId`, then on to `toNodeId`.
   */
  dispatchVehicle(options: {
    readonly kind?: VehicleKind;
    readonly toNodeId: EntityId;
    readonly fromNodeId?: EntityId;
    readonly spawnAtNodeId?: EntityId;
    readonly loop?: boolean;
    readonly routeKind?: VehicleRoute['kind'];
    readonly corridorKey?: string | null;
    readonly serviceMinutes?: number;
    readonly ownerCompanyId?: EntityId | null;
  }): Vehicle | null {
    if (!options || !options.toNodeId) {
      throw new TypeError('dispatchVehicle(options) expects options.toNodeId');
    }
    if (!this.nodeById.has(options.toNodeId)) {
      throw new RangeError(`dispatchVehicle(...) received unknown road node ${options.toNodeId}`);
    }
    const fromNodeId = options.fromNodeId ?? this.depotNodeId;
    if (!this.nodeById.has(fromNodeId)) {
      throw new RangeError(`dispatchVehicle(...) received unknown road node ${fromNodeId}`);
    }
    const spawnAtNodeId = options.spawnAtNodeId ?? this.depotNodeId;
    if (!this.nodeById.has(spawnAtNodeId)) {
      throw new RangeError(`dispatchVehicle(...) received unknown road node ${spawnAtNodeId}`);
    }
    if (this.activeRuntimes.length >= this.maxActiveVehicles) {
      this.unservedIntentValue += 1;
      return null;
    }
    const kind = options.kind ?? 'car';
    const spec = VEHICLE_KIND_SPECS[kind];
    return this.spawnVehicle({
      kind,
      role: spec.role,
      stops: [
        { nodeId: fromNodeId, buildingId: null, action: 'board', dwellMinutes: spec.dwellMinutes },
        { nodeId: options.toNodeId, buildingId: null, action: 'alight', dwellMinutes: spec.dwellMinutes },
      ],
      loop: options.loop ?? false,
      routeKind: options.routeKind ?? 'shuttle',
      spawnAtNodeId,
      corridorKey: options.corridorKey ?? null,
      coverageSlot: null,
      serviceUntilMinute: this.serviceUntilFrom(options.serviceMinutes),
      ownerCompanyId: options.ownerCompanyId ?? this.ownerForRole(spec.role),
    });
  }

  /** Absolute sim-minute a run ends at, from a run length in minutes. */
  private serviceUntilFrom(serviceMinutes?: number): number {
    if (serviceMinutes === undefined || !Number.isFinite(serviceMinutes)) {
      return Number.POSITIVE_INFINITY;
    }
    return this.absoluteMinuteValue + serviceMinutes;
  }

  /** Dispatches a delivery van along one freight corridor. */
  dispatchFreightRun(run: FreightRun, options: { loop?: boolean } = {}): Vehicle | null {
    if (this.activeRuntimes.length >= this.maxActiveVehicles) {
      this.unservedIntentValue += 1;
      return null;
    }
    const spec = VEHICLE_KIND_SPECS[run.vehicleKind];
    return this.spawnVehicle({
      kind: run.vehicleKind,
      role: 'freight',
      stops: [
        {
          nodeId: run.sourceNodeId,
          buildingId: run.sourceBuildingId,
          action: 'service',
          dwellMinutes: spec.dwellMinutes,
        },
        {
          nodeId: run.destinationNodeId,
          buildingId: run.destinationBuildingId,
          action: 'service',
          dwellMinutes: spec.dwellMinutes,
        },
      ],
      loop: options.loop ?? false,
      routeKind: 'delivery',
      spawnAtNodeId: this.depotNodeId,
      corridorKey: `freight:${run.id}`,
      coverageSlot: null,
      serviceUntilMinute: this.absoluteMinuteValue + FREIGHT_SERVICE_MINUTES,
      ownerCompanyId: this.ownerForRole('freight'),
    });
  }

  /** Dispatches a transit vehicle that works one commuter corridor. */
  dispatchTransitCorridor(corridor: CommuteCorridor, options: { loop?: boolean } = {}): Vehicle | null {
    if (this.activeRuntimes.length >= this.maxActiveVehicles) {
      this.unservedIntentValue += 1;
      return null;
    }
    const kind: VehicleKind = corridor.kind === 'tram' ? 'tram' : 'bus';
    const spec = VEHICLE_KIND_SPECS[kind];
    return this.spawnVehicle({
      kind,
      role: 'transit',
      stops: [
        {
          nodeId: corridor.fromNodeId,
          buildingId: corridor.fromBuildingId,
          action: 'board',
          dwellMinutes: spec.dwellMinutes,
        },
        {
          nodeId: corridor.toNodeId,
          buildingId: corridor.toBuildingId,
          action: 'alight',
          dwellMinutes: spec.dwellMinutes,
        },
      ],
      loop: options.loop ?? true,
      routeKind: 'shuttle',
      spawnAtNodeId: this.depotNodeId,
      corridorKey: `${kind}:${corridor.fromBuildingId}>${corridor.toBuildingId}`,
      coverageSlot: null,
      serviceUntilMinute: this.absoluteMinuteValue + TRANSIT_SERVICE_MINUTES,
      ownerCompanyId: this.ownerForRole('transit'),
    });
  }

  /* -------------------------------------------------------------- demand -- */

  /** Riders waiting at one node, for tests and the inspector. */
  waitingAt(nodeId: EntityId): readonly VehiclePassenger[] {
    return (this.waitingByNode.get(nodeId) ?? []).map((rider) => ({
      citizenId: rider.citizenId,
      originBuildingId: rider.originBuildingId,
      destinationBuildingId: rider.destinationBuildingId,
      destinationNodeId: rider.destinationNodeId,
      boardedAtMinute: rider.boardedAtMinute,
    }));
  }

  /** Turns every new commute intent into a ride, or shares an existing one. */
  private servePendingIntents(): void {
    if (this.citizens === null) {
      return;
    }
    for (const intent of this.citizens.pendingCommuteIntents()) {
      const kind = vehicleKindForCommuteMode(intent.mode);
      if (kind === null) {
        continue;
      }
      const key = `${intent.citizenId}:${Math.round(intent.departMinute)}:${intent.fromBuildingId}>${intent.toBuildingId}`;
      if (this.servedIntentKeys.has(key)) {
        continue;
      }
      this.servedIntentKeys.add(key);
      const originNodeId = this.nodeForBuilding(intent.fromBuildingId);
      const destinationNodeId = this.nodeForBuilding(intent.toBuildingId);
      if (!originNodeId || !destinationNodeId) {
        this.unservedIntentValue += 1;
        continue;
      }
      if (originNodeId === destinationNodeId) {
        // Both buildings open onto the same road node: that is a walk, not a ride.
        continue;
      }
      const rider = this.riderForIntent(intent, kind, originNodeId, destinationNodeId);
      const existing = this.findServableVehicle(kind, rider);
      this.registerWaitingRider(rider);
      if (existing) {
        continue;
      }
      if (this.dispatchRideVehicle(kind, rider) === null) {
        // Fleet cap reached: the commuter keeps their own two feet.
        this.removeWaitingRider(rider.originNodeId, rider);
      }
    }
  }

  private riderForIntent(
    intent: CommuteIntent,
    kind: VehicleKind,
    originNodeId: EntityId,
    destinationNodeId: EntityId,
  ): FleetRider {
    const allowedKinds: readonly VehicleKind[] =
      kind === 'car' ? ['car', 'taxi'] : [kind];
    return {
      citizenId: intent.citizenId,
      mode: intent.mode,
      corridorKey: `${kind}:${intent.fromBuildingId}>${intent.toBuildingId}`,
      originBuildingId: intent.fromBuildingId,
      destinationBuildingId: intent.toBuildingId,
      originNodeId,
      destinationNodeId,
      allowedKinds,
      departMinute: intent.departMinute,
      expiresAtMinute: this.absoluteMinuteValue + MAX_RIDER_WAIT_MINUTES,
      vehicleId: null,
      boardedAtMinute: this.minuteOfDayValue,
    };
  }

  private dispatchRideVehicle(kind: VehicleKind, rider: FleetRider): Vehicle | null {
    if (this.activeRuntimes.length >= this.maxActiveVehicles) {
      this.unservedIntentValue += 1;
      return null;
    }
    const spec = VEHICLE_KIND_SPECS[kind];
    const role: VehicleRole = spec.role;
    return this.spawnVehicle({
      kind,
      role,
      stops: [
        {
          nodeId: rider.originNodeId,
          buildingId: rider.originBuildingId,
          action: 'board',
          dwellMinutes: spec.dwellMinutes,
        },
        {
          nodeId: rider.destinationNodeId,
          buildingId: rider.destinationBuildingId,
          action: 'alight',
          dwellMinutes: spec.dwellMinutes,
        },
      ],
      loop: false,
      routeKind: 'shuttle',
      spawnAtNodeId: rider.originNodeId,
      corridorKey: rider.corridorKey,
      coverageSlot: null,
      serviceUntilMinute: Number.POSITIVE_INFINITY,
      ownerCompanyId: this.ownerForRole(role),
    });
  }

  /** A vehicle already dwelling at the rider's stop that can take them. */
  private findServableVehicle(kind: VehicleKind, rider: FleetRider): VehicleRuntime | null {
    for (const runtime of this.activeRuntimes) {
      if (runtime.vehicle.kind !== kind || runtime.activity !== 'dwelling') {
        continue;
      }
      if (runtime.vehicle.currentNodeId !== rider.originNodeId) {
        continue;
      }
      if (this.canServe(runtime, rider)) {
        return runtime;
      }
    }
    return null;
  }

  private registerWaitingRider(rider: FleetRider): void {
    const waiting = this.waitingByNode.get(rider.originNodeId) ?? [];
    waiting.push(rider);
    this.waitingByNode.set(rider.originNodeId, waiting);
  }

  private removeWaitingRider(nodeId: EntityId, rider: FleetRider): void {
    const waiting = this.waitingByNode.get(nodeId);
    if (!waiting) {
      return;
    }
    const index = waiting.indexOf(rider);
    if (index >= 0) {
      waiting.splice(index, 1);
    }
    if (waiting.length === 0) {
      this.waitingByNode.delete(nodeId);
    }
  }

  /** Drops riders whose ride never came; their commute is over either way. */
  private expireWaitingRiders(): void {
    for (const [nodeId, riders] of [...this.waitingByNode]) {
      for (const rider of [...riders]) {
        if (rider.expiresAtMinute <= this.absoluteMinuteValue) {
          this.removeWaitingRider(nodeId, rider);
          this.expiredWaitValue += 1;
        }
      }
    }
  }

  /* ------------------------------------------------------- scheduled fleet -- */

  /** Tops the fleet up to the floor the current hour calls for. */
  private ensureCoverage(): void {
    const target = this.targetFleetSize();
    let attempts = 0;
    while (this.activeRuntimes.length < target && attempts < COVERAGE_PLAN.length * 2) {
      attempts += 1;
      if (!this.dispatchNextCoverageSlot(target)) {
        break;
      }
    }
  }

  /** Vehicles the fleet should hold on the road at the current minute. */
  private targetFleetSize(): number {
    const hour = Math.floor(this.minuteOfDayValue / MINUTES_PER_HOUR) % 24;
    if (hour >= SERVICE_START_HOUR && hour < SERVICE_END_HOUR) {
      return this.serviceFleetSize;
    }
    return Math.min(this.nightFleetSize, this.serviceFleetSize);
  }

  /** Dispatches the first coverage slot that is not already running. */
  private dispatchNextCoverageSlot(target: number): boolean {
    for (let slotIndex = 0; slotIndex < target; slotIndex += 1) {
      if (this.coverageAssignments.has(slotIndex)) {
        continue;
      }
      if (this.dispatchCoverageSlot(slotIndex)) {
        return true;
      }
    }
    return false;
  }

  private dispatchCoverageSlot(slotIndex: number): boolean {
    const slot = COVERAGE_PLAN[slotIndex % COVERAGE_PLAN.length];
    const spec = VEHICLE_KIND_SPECS[slot.kind];
    if (slot.role === 'transit') {
      const corridor = this.nextCorridor(slot.kind === 'tram' ? 'tram' : 'bus');
      if (!corridor) {
        return false;
      }
      this.spawnVehicle({
        kind: slot.kind,
        role: 'transit',
        stops: [
          {
            nodeId: corridor.fromNodeId,
            buildingId: corridor.fromBuildingId,
            action: 'board',
            dwellMinutes: spec.dwellMinutes,
          },
          {
            nodeId: corridor.toNodeId,
            buildingId: corridor.toBuildingId,
            action: 'alight',
            dwellMinutes: spec.dwellMinutes,
          },
        ],
        loop: true,
        routeKind: 'shuttle',
        spawnAtNodeId: this.depotNodeId,
        corridorKey: `${slot.kind}:${corridor.fromBuildingId}>${corridor.toBuildingId}`,
        coverageSlot: slotIndex,
        serviceUntilMinute: this.absoluteMinuteValue + TRANSIT_SERVICE_MINUTES,
        ownerCompanyId: this.ownerForRole('transit'),
      });
      return true;
    }
    if (slot.role === 'freight') {
      const run = this.nextFreightRun();
      if (!run) {
        return false;
      }
      this.spawnVehicle({
        kind: slot.kind,
        role: 'freight',
        stops: [
          {
            nodeId: run.sourceNodeId,
            buildingId: run.sourceBuildingId,
            action: 'service',
            dwellMinutes: spec.dwellMinutes,
          },
          {
            nodeId: run.destinationNodeId,
            buildingId: run.destinationBuildingId,
            action: 'service',
            dwellMinutes: spec.dwellMinutes,
          },
        ],
        loop: true,
        routeKind: 'delivery',
        spawnAtNodeId: this.depotNodeId,
        corridorKey: `freight:${run.id}`,
        coverageSlot: slotIndex,
        serviceUntilMinute: this.absoluteMinuteValue + FREIGHT_SERVICE_MINUTES,
        ownerCompanyId: this.ownerForRole('freight'),
      });
      return true;
    }
    const corridor = this.nextCorridor('car');
    if (!corridor) {
      return false;
    }
    // Pre-positioned ride: it waits at the kerb the commuters leave from.
    this.spawnVehicle({
      kind: slot.kind,
      role: 'commute',
      stops: [
        {
          nodeId: corridor.fromNodeId,
          buildingId: corridor.fromBuildingId,
          action: 'board',
          dwellMinutes: Math.max(PREPOSITIONED_WAIT_MINUTES, spec.dwellMinutes),
        },
        {
          nodeId: corridor.toNodeId,
          buildingId: corridor.toBuildingId,
          action: 'alight',
          dwellMinutes: spec.dwellMinutes,
        },
      ],
      loop: false,
      routeKind: 'shuttle',
      spawnAtNodeId: corridor.fromNodeId,
      corridorKey: `${slot.kind}:${corridor.fromBuildingId}>${corridor.toBuildingId}`,
      coverageSlot: slotIndex,
      serviceUntilMinute: Number.POSITIVE_INFINITY,
      ownerCompanyId: this.ownerForRole('commute'),
    });
    return true;
  }

  /** Next corridor for a role, spread deterministically over the busiest. */
  private nextCorridor(kind: 'car' | 'bus' | 'tram' | 'bicycle'): CommuteCorridor | null {
    const preferred: ('car' | 'bus' | 'tram' | 'bicycle')[] =
      kind === 'bus'
        ? ['bus', 'tram', 'car']
        : kind === 'tram'
          ? ['tram', 'bus', 'car']
          : kind === 'car'
            ? ['car', 'bus', 'tram']
            : ['bicycle', 'car', 'bus'];
    for (const candidate of preferred) {
      const pool = this.corridorsByKind[candidate];
      if (pool.length === 0) {
        continue;
      }
      const spread = Math.min(CORRIDOR_CHOICE_SPREAD, pool.length);
      const choice = this.rng.intInclusive(0, spread - 1);
      const cursor = this.corridorCursor[candidate] + choice;
      this.corridorCursor[candidate] = (this.corridorCursor[candidate] + 1) % pool.length;
      return pool[cursor % pool.length];
    }
    return null;
  }

  private nextFreightRun(): FreightRun | null {
    if (this.freightRunList.length === 0) {
      return null;
    }
    const index = this.coverageAssignments.size % this.freightRunList.length;
    return this.freightRunList[index];
  }

  /* --------------------------------------------------------------- driving -- */

  private advanceFleet(deltaMinutes: number): void {
    const claims = this.claimNodes();
    for (const runtime of [...this.activeRuntimes]) {
      if (!this.runtimeById.has(runtime.vehicle.id)) {
        continue;
      }
      if (runtime.activity === 'dwelling') {
        runtime.vehicle.speed = 0;
        this.boardWaitingRiders(runtime);
        runtime.dwellRemaining -= deltaMinutes;
        if (runtime.dwellRemaining <= 1e-9) {
          this.finishDwell(runtime);
        }
        continue;
      }
      this.driveVehicle(runtime, claims, deltaMinutes);
    }
  }

  /** Nodes claimed for this tick: the closest vehicle to each node wins. */
  private claimNodes(): Map<EntityId, EntityId> {
    const contenders: { nodeId: EntityId; vehicleId: EntityId; distance: number }[] = [];
    for (const runtime of this.activeRuntimes) {
      if (runtime.activity !== 'driving') {
        continue;
      }
      const nodeId = runtime.leg.nodeIds[runtime.leg.index];
      if (!nodeId) {
        continue;
      }
      const distance = runtime.leg.length - runtime.leg.travelled;
      if (distance <= NODE_ZONE_TILES) {
        contenders.push({ nodeId, vehicleId: runtime.vehicle.id, distance });
      }
    }
    contenders.sort(
      (left, right) =>
        left.distance - right.distance || compareIds(left.vehicleId, right.vehicleId),
    );
    const claims = new Map<EntityId, EntityId>();
    for (const contender of contenders) {
      if (!claims.has(contender.nodeId)) {
        claims.set(contender.nodeId, contender.vehicleId);
      }
    }
    return claims;
  }

  private driveVehicle(
    runtime: VehicleRuntime,
    claims: Map<EntityId, EntityId>,
    deltaMinutes: number,
  ): void {
    const freeSpeed = this.freeSpeedFor(runtime);
    const decision = this.planSpeed(runtime, claims, freeSpeed, deltaMinutes);
    runtime.vehicle.speed = decision.speed;
    if (decision.yielding) {
      if (runtime.yieldSinceMinute === null) {
        runtime.yieldSinceMinute = this.absoluteMinuteValue;
        this.yieldStartValue += 1;
      }
      this.yieldTickValue += 1;
    } else {
      runtime.yieldSinceMinute = null;
    }
    if (decision.following) {
      this.followTickValue += 1;
    }
    if (decision.speed <= 0) {
      this.updatePosition(runtime);
      return;
    }
    this.integrate(runtime, decision.speed * deltaMinutes);
    this.updatePosition(runtime);
  }

  /** Free-flow speed for a vehicle on its current segment. */
  private freeSpeedFor(runtime: VehicleRuntime): number {
    const segment = runtime.leg.segmentId ? this.segmentById.get(runtime.leg.segmentId) ?? null : null;
    const limit = segment
      ? segment.speedLimit
      : this.nodeById.get(runtime.leg.toNodeId)?.speedLimit ?? VEHICLE_KIND_SPECS[runtime.vehicle.kind].maxSpeed;
    return Math.max(0.05, pacedSpeedLimit(limit, runtime.vehicle.kind));
  }

  /**
   * Speed for this tick: free flow, capped by the vehicle ahead (car following)
   * and by an intersection claim held by somebody else (yielding).
   */
  private planSpeed(
    runtime: VehicleRuntime,
    claims: Map<EntityId, EntityId>,
    freeSpeed: number,
    deltaMinutes: number,
  ): { speed: number; yielding: boolean; following: boolean } {
    let speed = freeSpeed;
    let following = false;

    let closestGap = Number.POSITIVE_INFINITY;
    for (const other of this.activeRuntimes) {
      if (other === runtime || other.leg.segmentId === null) {
        continue;
      }
      if (other.leg.segmentId !== runtime.leg.segmentId || other.leg.fromNodeId !== runtime.leg.fromNodeId) {
        continue;
      }
      if (!isAheadOnLeg(other, runtime)) {
        continue;
      }
      const gap = other.leg.travelled - runtime.leg.travelled - other.spec.lengthTiles * 0.5;
      if (gap < closestGap) {
        closestGap = gap;
      }
    }
    if (closestGap < Number.POSITIVE_INFINITY) {
      const safe = Math.max(0, (closestGap - FOLLOW_GAP_TILES) / FOLLOW_HEADWAY_MINUTES);
      if (safe < speed) {
        following = true;
        speed = safe;
      }
    }

    const targetNodeId = runtime.leg.nodeIds[runtime.leg.index];
    const distance = runtime.leg.length - runtime.leg.travelled;
    const yieldDistance = Math.max(NODE_ZONE_TILES, freeSpeed * deltaMinutes) + NODE_YIELD_DISTANCE_TILES;
    const claimant = targetNodeId ? claims.get(targetNodeId) ?? null : null;
    if (claimant !== null && claimant !== runtime.vehicle.id && distance <= yieldDistance) {
      const waited =
        runtime.yieldSinceMinute === null ? 0 : this.absoluteMinuteValue - runtime.yieldSinceMinute;
      if (waited < MAX_YIELD_MINUTES) {
        return { speed: 0, yielding: true, following };
      }
      // Patience ran out: creep across instead of gridlocking the block.
      speed = Math.min(speed, freeSpeed * YIELD_CREEP_FACTOR);
    }
    return { speed: clamp(speed, 0, runtime.spec.maxSpeed), yielding: false, following };
  }

  /** Moves a vehicle along its leg, arriving at nodes as it goes. */
  private integrate(runtime: VehicleRuntime, budgetTiles: number): void {
    let remaining = budgetTiles;
    for (let guard = 0; guard < MAX_SEGMENTS_PER_TICK && remaining > 0; guard += 1) {
      if (runtime.activity !== 'driving') {
        return;
      }
      const legRemaining = runtime.leg.length - runtime.leg.travelled;
      if (legRemaining <= 0) {
        this.arriveAtNode(runtime, runtime.leg.nodeIds[runtime.leg.index]);
        continue;
      }
      if (remaining < legRemaining) {
        runtime.leg.travelled += remaining;
        this.consumeFuel(runtime, remaining);
        this.distanceValue += remaining;
        runtime.distanceTiles += remaining;
        return;
      }
      runtime.leg.travelled = runtime.leg.length;
      this.consumeFuel(runtime, legRemaining);
      this.distanceValue += legRemaining;
      runtime.distanceTiles += legRemaining;
      remaining -= legRemaining;
      this.updatePosition(runtime);
      this.arriveAtNode(runtime, runtime.leg.nodeIds[runtime.leg.index]);
    }
  }

  private consumeFuel(runtime: VehicleRuntime, tiles: number): void {
    const vehicle = runtime.vehicle;
    vehicle.fuel = clamp(vehicle.fuel - runtime.spec.fuelPerTile * tiles, 0, vehicle.fuelCapacity);
    if (vehicle.fuel <= 0 && !runtime.retiring) {
      runtime.retiring = true;
    }
  }

  private updatePosition(runtime: VehicleRuntime): void {
    const from = this.nodeById.get(runtime.leg.fromNodeId);
    const to = this.nodeById.get(runtime.leg.toNodeId);
    if (!from || !to) {
      return;
    }
    const ratio = runtime.leg.length > 0 ? clamp(runtime.leg.travelled / runtime.leg.length, 0, 1) : 1;
    runtime.vehicle.position = {
      x: from.x + (to.x - from.x) * ratio,
      y: from.y + (to.y - from.y) * ratio,
    };
    runtime.vehicle.headingRadians = Math.atan2(to.y - from.y, to.x - from.x);
  }

  private enterSegment(
    runtime: VehicleRuntime,
    fromNodeId: EntityId,
    toNodeId: EntityId,
    index: number,
  ): void {
    const from = this.nodeById.get(fromNodeId);
    const to = this.nodeById.get(toNodeId);
    const length = from && to ? distanceBetweenPoints(from, to) : 0;
    runtime.leg = {
      nodeIds: runtime.leg.nodeIds,
      index,
      fromNodeId,
      toNodeId,
      segmentId: this.segmentIdBetween(fromNodeId, toNodeId),
      length,
      travelled: 0,
    };
    runtime.vehicle.targetNodeId = toNodeId;
  }

  private segmentIdBetween(fromNodeId: EntityId, toNodeId: EntityId): EntityId | null {
    const from = this.nodeById.get(fromNodeId);
    if (from && !from.neighborIds.includes(toNodeId)) {
      return null;
    }
    for (const segment of this.world.segments) {
      if (
        (segment.fromNodeId === fromNodeId && segment.toNodeId === toNodeId) ||
        (segment.fromNodeId === toNodeId && segment.toNodeId === fromNodeId)
      ) {
        return segment.id;
      }
    }
    return null;
  }

  /** Plans the leg towards the next stop, or starts the dwell right away. */
  private planNextLeg(runtime: VehicleRuntime): void {
    if (runtime.stopIndex >= runtime.stops.length) {
      this.parkVehicle(runtime);
      return;
    }
    const stop = runtime.stops[runtime.stopIndex];
    const fromNodeId = runtime.vehicle.currentNodeId;
    if (fromNodeId === null) {
      this.parkVehicle(runtime);
      return;
    }
    if (fromNodeId === stop.nodeId) {
      runtime.activity = 'dwelling';
      runtime.dwellRemaining = Math.max(0, stop.dwellMinutes);
      runtime.vehicle.speed = 0;
      runtime.vehicle.targetNodeId = null;
      this.boardWaitingRiders(runtime);
      return;
    }
    const route = this.world.routeBetweenNodes(fromNodeId, stop.nodeId);
    if (!route || route.nodeIds.length < 2) {
      this.parkVehicle(runtime);
      return;
    }
    runtime.leg.nodeIds = route.nodeIds.slice();
    runtime.activity = 'driving';
    this.enterSegment(runtime, route.nodeIds[0], route.nodeIds[1], 1);
    this.syncRouteStops(runtime);
    this.updatePosition(runtime);
  }

  private arriveAtNode(runtime: VehicleRuntime, nodeId: EntityId): void {
    runtime.vehicle.currentNodeId = nodeId;
    runtime.leg.travelled = runtime.leg.length;
    this.updatePosition(runtime);
    this.alightRidersAt(runtime, nodeId);
    const stop = runtime.stops[runtime.stopIndex] ?? null;
    if (stop && stop.nodeId === nodeId) {
      runtime.activity = 'dwelling';
      runtime.dwellRemaining = Math.max(0, stop.dwellMinutes);
      runtime.vehicle.speed = 0;
      runtime.vehicle.targetNodeId = null;
      this.boardWaitingRiders(runtime);
      return;
    }
    this.advanceLeg(runtime);
  }

  private advanceLeg(runtime: VehicleRuntime): void {
    const nextIndex = runtime.leg.index + 1;
    if (nextIndex < runtime.leg.nodeIds.length) {
      this.enterSegment(
        runtime,
        runtime.leg.nodeIds[nextIndex - 1],
        runtime.leg.nodeIds[nextIndex],
        nextIndex,
      );
      return;
    }
    this.planNextLeg(runtime);
  }

  /** Ends a stop: retires the run, loops the route or drives on. */
  private finishDwell(runtime: VehicleRuntime): void {
    const stop = runtime.stops[runtime.stopIndex] ?? null;
    if (stop && stop.action === 'service') {
      this.deliveryValue += 1;
    }
    runtime.stopIndex += 1;
    this.boardWaitingRiders(runtime);
    if (
      Number.isFinite(runtime.serviceUntilMinute) &&
      this.absoluteMinuteValue >= runtime.serviceUntilMinute
    ) {
      runtime.retiring = true;
    }
    if (runtime.retiring) {
      if (runtime.vehicle.currentNodeId === this.depotNodeId) {
        this.parkVehicle(runtime);
        return;
      }
      this.sendToDepot(runtime);
      return;
    }
    if (runtime.stopIndex >= runtime.stops.length) {
      if (runtime.vehicle.route.loop) {
        runtime.stopIndex = 0;
        this.planNextLeg(runtime);
        return;
      }
      runtime.completedTrips += 1;
      this.parkVehicle(runtime);
      return;
    }
    this.planNextLeg(runtime);
  }

  private sendToDepot(runtime: VehicleRuntime): void {
    runtime.retiring = true;
    runtime.stops = [{ nodeId: this.depotNodeId, buildingId: null, action: 'park', dwellMinutes: 0 }];
    runtime.stopIndex = 0;
    this.syncRouteStops(runtime);
    this.planNextLeg(runtime);
  }

  /** Parking, refuelling and returning the object to the reuse pool. */
  private parkVehicle(runtime: VehicleRuntime): void {
    if (!this.runtimeById.delete(runtime.vehicle.id)) {
      return;
    }
    const index = this.activeRuntimes.indexOf(runtime);
    if (index >= 0) {
      this.activeRuntimes.splice(index, 1);
    }
    if (runtime.coverageSlot !== null) {
      this.coverageAssignments.delete(runtime.coverageSlot);
    }
    for (const rider of [...runtime.riders]) {
      this.alightRider(runtime, rider, runtime.vehicle.currentNodeId);
    }
    const worldIndex = this.world.vehicles.indexOf(runtime.vehicle);
    if (worldIndex >= 0) {
      this.world.vehicles.splice(worldIndex, 1);
    }
    runtime.activity = 'parked';
    runtime.vehicle.speed = 0;
    runtime.vehicle.targetNodeId = null;
    this.logEvent('park', runtime.vehicle, {
      role: runtime.role,
      citizenId: null,
      buildingId: null,
      nodeId: runtime.vehicle.currentNodeId,
    });
    this.parkCountValue += 1;
    runtime.vehicle.fuel = runtime.vehicle.fuelCapacity;
    this.refuelCountValue += 1;
    runtime.vehicle.occupancy = 0;
    runtime.vehicle.occupantIds.length = 0;
    runtime.vehicle.route = {
      id: `route-${runtime.vehicle.id}`,
      kind: 'shuttle',
      stopNodeIds: [],
      loop: false,
    };
    runtime.stops = [];
    runtime.stopIndex = 0;
    this.poolByKind.get(runtime.vehicle.kind)?.push(runtime.vehicle);
  }

  /* ------------------------------------------------------------- boarding -- */

  private boardWaitingRiders(runtime: VehicleRuntime): void {
    const nodeId = runtime.vehicle.currentNodeId;
    if (nodeId === null) {
      return;
    }
    const waiting = this.waitingByNode.get(nodeId);
    if (!waiting || waiting.length === 0) {
      return;
    }
    for (const rider of [...waiting]) {
      if (runtime.vehicle.occupancy >= runtime.vehicle.capacity) {
        return;
      }
      if (!this.canServe(runtime, rider)) {
        continue;
      }
      this.planDestinationStop(runtime, rider.destinationNodeId, rider.destinationBuildingId);
      rider.vehicleId = runtime.vehicle.id;
      rider.boardedAtMinute = this.minuteOfDayValue;
      runtime.riders.push(rider);
      runtime.vehicle.occupantIds.push(rider.citizenId);
      this.removeWaitingRider(nodeId, rider);
      runtime.vehicle.occupancy = runtime.vehicle.occupantIds.length;
      this.boardCountValue += 1;
      this.logEvent('board', runtime.vehicle, {
        role: runtime.role,
        citizenId: rider.citizenId,
        buildingId: rider.originBuildingId,
        nodeId,
      });
      this.linkCitizen(rider.citizenId, runtime.vehicle.id);
    }
  }

  private canServe(runtime: VehicleRuntime, rider: FleetRider): boolean {
    if (rider.vehicleId !== null) {
      return false;
    }
    if (runtime.role === 'freight' || runtime.activity === 'parked') {
      return false;
    }
    if (runtime.vehicle.occupancy >= runtime.vehicle.capacity) {
      return false;
    }
    if (!rider.allowedKinds.includes(runtime.vehicle.kind)) {
      return false;
    }
    if (runtime.role === 'commute') {
      const corridorMatch =
        runtime.corridorKey !== null && runtime.corridorKey === rider.corridorKey;
      if (!corridorMatch && !this.planHasStopAhead(runtime, rider.destinationNodeId)) {
        return false;
      }
    }
    return true;
  }

  private planHasStopAhead(runtime: VehicleRuntime, nodeId: EntityId): boolean {
    for (let index = runtime.stopIndex; index < runtime.stops.length; index += 1) {
      if (runtime.stops[index].nodeId === nodeId) {
        return true;
      }
    }
    return false;
  }

  /** Inserts the drop-off stop right after the stop the vehicle is at. */
  private planDestinationStop(runtime: VehicleRuntime, nodeId: EntityId, buildingId: EntityId): void {
    for (let index = runtime.stopIndex + 1; index < runtime.stops.length; index += 1) {
      if (runtime.stops[index].nodeId === nodeId) {
        return;
      }
    }
    runtime.stops.splice(runtime.stopIndex + 1, 0, {
      nodeId,
      buildingId,
      action: 'alight',
      dwellMinutes: runtime.spec.dwellMinutes,
    });
    this.syncRouteStops(runtime);
  }

  private syncRouteStops(runtime: VehicleRuntime): void {
    runtime.vehicle.route = {
      ...runtime.vehicle.route,
      stopNodeIds: runtime.stops.map((stop) => stop.nodeId),
    };
  }

  private alightRidersAt(runtime: VehicleRuntime, nodeId: EntityId): void {
    for (const rider of [...runtime.riders]) {
      if (rider.destinationNodeId === nodeId) {
        this.alightRider(runtime, rider, nodeId);
      }
    }
  }

  private alightRider(runtime: VehicleRuntime, rider: FleetRider, nodeId: EntityId | null): void {
    const index = runtime.riders.indexOf(rider);
    if (index >= 0) {
      runtime.riders.splice(index, 1);
    }
    const occupantIndex = runtime.vehicle.occupantIds.indexOf(rider.citizenId);
    if (occupantIndex >= 0) {
      runtime.vehicle.occupantIds.splice(occupantIndex, 1);
    }
    runtime.vehicle.occupancy = runtime.vehicle.occupantIds.length;
    rider.vehicleId = null;
    this.unlinkCitizen(rider.citizenId, runtime.vehicle.id);
    this.alightCountValue += 1;
    this.logEvent('alight', runtime.vehicle, {
      role: runtime.role,
      citizenId: rider.citizenId,
      buildingId: rider.destinationBuildingId,
      nodeId,
    });
  }

  /* ------------------------------------------------------------ rider link -- */

  /** Rewrites `Citizen.vehicleId` for every rider the fleet carries. */
  private syncRiderLinks(): void {
    for (const runtime of this.activeRuntimes) {
      for (const rider of runtime.riders) {
        this.linkCitizen(rider.citizenId, runtime.vehicle.id);
      }
    }
  }

  private linkCitizen(citizenId: EntityId, vehicleId: EntityId): void {
    const citizen = this.citizenById(citizenId);
    if (citizen) {
      citizen.vehicleId = vehicleId;
    }
  }

  private unlinkCitizen(citizenId: EntityId, vehicleId: EntityId): void {
    const citizen = this.citizenById(citizenId);
    if (citizen && citizen.vehicleId === vehicleId) {
      citizen.vehicleId = null;
    }
  }

  private citizenById(citizenId: EntityId): Citizen | null {
    return this.citizenIndex.get(citizenId) ?? this.citizens?.citizenById(citizenId) ?? null;
  }

  /* ---------------------------------------------------------- spawning -- */

  private spawnVehicle(request: SpawnRequest): Vehicle {
    const spec = VEHICLE_KIND_SPECS[request.kind];
    const pool = this.poolByKind.get(request.kind) ?? [];
    const reused = pool.pop() ?? null;
    const vehicle = reused ?? this.createVehicle(request.kind, spec);
    if (reused) {
      this.reuseCountValue += 1;
    } else {
      this.createdVehicleCountValue += 1;
    }
    const spawnNode = this.nodeById.get(request.spawnAtNodeId) ?? null;
    vehicle.occupancy = 0;
    vehicle.occupantIds.length = 0;
    vehicle.speed = 0;
    vehicle.fuel = vehicle.fuelCapacity;
    vehicle.headingRadians = 0;
    vehicle.position = spawnNode ? { x: spawnNode.x, y: spawnNode.y } : { x: 0, y: 0 };
    vehicle.currentNodeId = request.spawnAtNodeId;
    vehicle.targetNodeId = null;
    vehicle.ownerCompanyId = request.ownerCompanyId;
    vehicle.route = {
      id: `route-${vehicle.id}`,
      kind: request.routeKind,
      stopNodeIds: request.stops.map((stop) => stop.nodeId),
      loop: request.loop,
    };

    const runtime: VehicleRuntime = {
      vehicle,
      spec,
      role: request.role,
      corridorKey: request.corridorKey,
      coverageSlot: request.coverageSlot,
      createdAtMinute: this.absoluteMinuteValue,
      serviceUntilMinute: request.serviceUntilMinute,
      stops: request.stops.map((stop) => ({ ...stop })),
      stopIndex: 0,
      leg: {
        nodeIds: [request.spawnAtNodeId],
        index: 0,
        fromNodeId: request.spawnAtNodeId,
        toNodeId: request.spawnAtNodeId,
        segmentId: null,
        length: 0,
        travelled: 0,
      },
      activity: 'dwelling',
      dwellRemaining: 0,
      riders: [],
      retiring: false,
      yieldSinceMinute: null,
      distanceTiles: 0,
      completedTrips: 0,
    };
    this.activeRuntimes.push(runtime);
    this.runtimeById.set(vehicle.id, runtime);
    if (!this.world.vehicles.includes(vehicle)) {
      this.world.vehicles.push(vehicle);
    }
    if (request.coverageSlot !== null) {
      this.coverageAssignments.set(request.coverageSlot, vehicle.id);
    }
    this.dispatchCountValue += 1;
    this.logEvent('dispatch', vehicle, {
      role: request.role,
      citizenId: null,
      buildingId: null,
      nodeId: request.spawnAtNodeId,
    });
    if (reused) {
      this.logEvent('reuse', vehicle, {
        role: request.role,
        citizenId: null,
        buildingId: null,
        nodeId: request.spawnAtNodeId,
      });
    }

    const firstStop = runtime.stops[runtime.stopIndex] ?? null;
    if (firstStop && firstStop.nodeId === vehicle.currentNodeId) {
      runtime.activity = 'dwelling';
      runtime.dwellRemaining = Math.max(0, firstStop.dwellMinutes);
      this.boardWaitingRiders(runtime);
    } else {
      runtime.activity = 'driving';
      this.planNextLeg(runtime);
    }
    return vehicle;
  }

  private createVehicle(kind: VehicleKind, spec: VehicleKindSpec): Vehicle {
    const serial = this.createdVehicleCountValue + 1;
    return {
      id: `vehicle-${serial}`,
      kind,
      plate: `${spec.platePrefix}-${1000 + serial}`,
      capacity: spec.capacity,
      route: { id: `route-vehicle-${serial}`, kind: 'shuttle', stopNodeIds: [], loop: false },
      occupancy: 0,
      occupantIds: [],
      fuel: spec.fuelCapacity,
      fuelCapacity: spec.fuelCapacity,
      speed: 0,
      headingRadians: 0,
      position: { x: 0, y: 0 },
      currentNodeId: null,
      targetNodeId: null,
      ownerCompanyId: null,
      color: spec.color,
    };
  }

  /* ------------------------------------------------------------- corridors -- */

  /** Tallies the commute corridors the roster actually travels. */
  private buildCorridors(): void {
    const legs = new Map<string, CommuteCorridor>();
    if (this.citizens !== null) {
      for (const citizen of this.citizens.activeCitizens()) {
        const routine = this.citizens.routineFor(citizen.id);
        if (!routine) {
          continue;
        }
        const kind = vehicleKindForCommuteMode(routine.commuteMode);
        if (kind === null) {
          continue;
        }
        for (const block of routine.blocks) {
          if (!block.stage.startsWith('commute-')) {
            continue;
          }
          const fromNodeId = this.nodeForBuilding(block.originId);
          const toNodeId = this.nodeForBuilding(block.destinationId);
          if (!fromNodeId || !toNodeId || fromNodeId === toNodeId) {
            continue;
          }
          const id = `${kind}:${block.originId}>${block.destinationId}`;
          const existing = legs.get(id);
          if (existing) {
            legs.set(id, { ...existing, legs: existing.legs + 1 });
          } else {
            legs.set(id, {
              id,
              kind,
              mode: routine.commuteMode,
              fromBuildingId: block.originId,
              toBuildingId: block.destinationId,
              fromNodeId,
              toNodeId,
              distanceTiles: round2(block.distanceTiles),
              legs: 1,
            });
          }
        }
      }
    }
    for (const corridor of this.fallbackCorridors()) {
      if (!legs.has(corridor.id)) {
        legs.set(corridor.id, corridor);
      }
    }
    const ordered = [...legs.values()].sort(
      (left, right) => right.legs - left.legs || compareIds(left.id, right.id),
    );
    for (const corridor of ordered) {
      this.corridorsByKind[corridor.kind as 'car' | 'bus' | 'tram' | 'bicycle'].push(corridor);
    }
  }

  /** Corridors derived from the world alone, for a fleet without a roster. */
  private fallbackCorridors(): CommuteCorridor[] {
    const homes = [...this.world.buildings]
      .filter((building) => building.kind === 'house' || building.kind === 'apartment')
      .sort((left, right) => right.capacity - left.capacity || compareIds(left.id, right.id));
    const workplaces = [...this.world.buildings]
      .filter((building) => WORKPLACE_KINDS.includes(building.kind))
      .sort((left, right) => compareIds(left.id, right.id));
    if (homes.length === 0 || workplaces.length === 0) {
      return [];
    }
    const corridors: CommuteCorridor[] = [];
    for (const home of homes.slice(0, 24)) {
      const homeCentre = buildingCenter(home);
      const sorted = [...workplaces].sort(
        (left, right) =>
          distanceBetweenPoints(buildingCenter(left), homeCentre) -
            distanceBetweenPoints(buildingCenter(right), homeCentre) ||
          compareIds(left.id, right.id),
      );
      for (const workplace of sorted.slice(0, 3)) {
        const fromNodeId = this.nodeForBuilding(home.id);
        const toNodeId = this.nodeForBuilding(workplace.id);
        if (!fromNodeId || !toNodeId || fromNodeId === toNodeId) {
          continue;
        }
        const kind: VehicleKind = corridors.length % 3 === 0 ? 'bus' : 'car';
        const id = `${kind}:${home.id}>${workplace.id}`;
        corridors.push({
          id,
          kind,
          mode: kind === 'bus' ? 'bus' : 'car',
          fromBuildingId: home.id,
          toBuildingId: workplace.id,
          fromNodeId,
          toNodeId,
          distanceTiles: 0,
          legs: 0,
        });
        break;
      }
    }
    return corridors;
  }

  /** Freight corridors: warehouse/factory to the nearest shop or store. */
  private buildFreightRuns(): FreightRun[] {
    const sources = [...this.world.buildings]
      .filter((building) => FREIGHT_SOURCE_KINDS.includes(building.kind))
      .sort((left, right) => compareIds(left.id, right.id));
    const destinations = [...this.world.buildings]
      .filter((building) => FREIGHT_DESTINATION_KINDS.includes(building.kind))
      .sort((left, right) => compareIds(left.id, right.id));
    const runs: FreightRun[] = [];
    for (const source of sources) {
      const sourceNodeId = this.nodeForBuilding(source.id);
      if (!sourceNodeId) {
        continue;
      }
      let best: FreightRun | null = null;
      for (const destination of destinations) {
        if (destination.id === source.id) {
          continue;
        }
        const destinationNodeId = this.nodeForBuilding(destination.id);
        if (!destinationNodeId || destinationNodeId === sourceNodeId) {
          continue;
        }
        const route = this.world.routeBetweenNodes(sourceNodeId, destinationNodeId);
        if (!route || route.distanceTiles < MIN_FREIGHT_DISTANCE_TILES) {
          continue;
        }
        if (
          best === null ||
          route.distanceTiles < best.distanceTiles ||
          (route.distanceTiles === best.distanceTiles &&
            compareIds(destination.id, best.destinationBuildingId) < 0)
        ) {
          best = {
            id: `${source.id}>${destination.id}`,
            vehicleKind: 'truck',
            sourceBuildingId: source.id,
            destinationBuildingId: destination.id,
            sourceNodeId,
            destinationNodeId,
            distanceTiles: round2(route.distanceTiles),
          };
        }
      }
      if (best) {
        runs.push(best);
      }
    }
    return runs;
  }

  /** Road node a building's traffic enters and leaves the network at. */
  private nodeForBuilding(buildingId: EntityId): EntityId | null {
    const building = this.buildingById.get(buildingId);
    if (!building) {
      return null;
    }
    if (building.entranceNodeId !== null && this.nodeById.has(building.entranceNodeId)) {
      return building.entranceNodeId;
    }
    return this.world.nearestRoadNode(buildingCenter(building)).id;
  }

  /** Owner a role reports to, when the city has a company in that sector. */
  private ownerForRole(role: VehicleRole): EntityId | null {
    const sector: CompanySector | null = role === 'transit' ? 'civic' : role === 'freight' ? 'logistics' : null;
    if (sector === null) {
      return null;
    }
    return this.companyBySector.get(sector) ?? null;
  }

  /* ---------------------------------------------------------------- events -- */

  private logEvent(
    kind: VehicleEventKind,
    vehicle: Vehicle,
    details: {
      role: VehicleRole;
      citizenId: EntityId | null;
      buildingId: EntityId | null;
      nodeId: EntityId | null;
    },
  ): void {
    this.eventLog.push({
      kind,
      vehicleId: vehicle.id,
      vehicleKind: vehicle.kind,
      role: details.role,
      citizenId: details.citizenId,
      buildingId: details.buildingId,
      nodeId: details.nodeId,
      day: this.dayValue,
      minuteOfDay: this.minuteOfDayValue,
      occupancy: vehicle.occupancy,
    });
    if (this.eventLog.length > EVENT_LOG_LIMIT) {
      this.eventLog.splice(0, this.eventLog.length - EVENT_LOG_LIMIT);
    }
  }
}

/** Builds a vehicle system for a world (and, in the app, a citizen roster). */
export function createVehiclesSystem(options: VehiclesOptions): VehiclesSystem {
  return new VehiclesSystem(options);
}

